export type AppRoute = "home" | "marketplace" | "create" | "workspace" | "workspace_records" | "manage_posts" | "workspace_responses" | "messages" | "notifications" | "payments" | "payment_list" | "settings" | "verification" | "admin" | "post" | "profile" | "member" | "respond" | "more" | "info";
export type MarketplaceTab = "requests" | "carry";
export type ServiceScope = "domestic" | "international";
export type NativeInfoSection = "about" | "how_it_works" | "safety" | "contact" | "downloads" | "legal" | "terms" | "privacy";

export type BridgeXProfile = {
  id: string;
  email?: string | null;
  full_name?: string | null;
  avatar_path?: string | null;
  role?: "member" | "admin" | "super_admin" | string | null;
  is_verified?: boolean | null;
  verification_status?: string | null;
  onboarding_complete?: boolean | null;
  suspended?: boolean | null;
  restriction_reason?: string | null;
  preferred_currency?: string | null;
  preferred_language?: string | null;
  phone?: string | null;
  current_country?: string | null;
  current_city?: string | null;
  current_address?: string | null;
  home_country?: string | null;
  home_city?: string | null;
  home_address?: string | null;
  china_address?: string | null;
};

export type MarketplacePost = {
  id: string;
  kind: MarketplaceTab;
  ownerId: string;
  title: string;
  route: string;
  price: number;
  currency: string;
  weight: string;
  category?: string | null;
  categories?: string[];
  description?: string | null;
  deliveryDays?: number | null;
  size?: string | null;
  specialHandling?: string | null;
  transportMode?: string | null;
  departureAt?: string | null;
  estimatedDeliveryAt?: string | null;
  acceptedItemQuantities?: Record<string, number>;
  acceptedItemBudgets?: Record<string, number>;
  transportProvider?: string | null;
  transportReference?: string | null;
  posterName?: string | null;
  posterVerified?: boolean;
  posterRating?: number;
  posterReviewCount?: number;
  createdAt: string;
  mediaPaths: string[];
  status: string;
};

export type NativeNotification = { id: string; title?: string | null; body?: string | null; created_at: string; read_at?: string | null; related_id?: string | null; type?: string | null; link?: string | null };
