import Ionicons from "@expo/vector-icons/Ionicons";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, FlatList, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { loadNativeAdminSection, markNativeAdminPayoutSent, moderateNativeAdminMarketplacePost, moderateNativeMember, reviewNativeVerification, saveNativeAdminExchangeRate, type NativeAdminRecord, type NativeAdminSection, updateNativeAdminOrder, updateNativeAdminReport, verifyNativeAdminPayment } from "../lib/api";
import { useBridgeXAppearance } from "../lib/appearance";
import { useNativeLanguage } from "../lib/i18n";

type Props = { role?: string | null };
type SectionCard = { key: NativeAdminSection; label: string; description: string; icon: keyof typeof Ionicons.glyphMap };
const sections: SectionCard[] = [
  { key: "users", label: "Users", description: "Search members and manage account access with recorded reasons.", icon: "people-outline" },
  { key: "verification", label: "Verification", description: "Review submitted identity records and decide approval or rejection.", icon: "shield-checkmark-outline" },
  { key: "payments", label: "Payment verification", description: "Review submitted payment records before opening protected matches.", icon: "card-outline" },
  { key: "payouts", label: "Traveler payouts", description: "Review payment-due payouts and record a transfer reference.", icon: "cash-outline" },
  { key: "orders", label: "Orders & escrow", description: "Apply authorised escrow and delivery-state actions.", icon: "cube-outline" },
  { key: "reports", label: "Reports", description: "Triage safety reports without exposing private evidence publicly.", icon: "alert-circle-outline" },
  { key: "requests", label: "Requests", description: "Moderate public send requests with a member-facing reason.", icon: "send-outline" },
  { key: "listings", label: "Carry listings", description: "Moderate live carry-space listings with a member-facing reason.", icon: "airplane-outline" },
  { key: "exchange_rates", label: "Payment exchange rates", description: "Publish the platform’s daily settlement exchange rate.", icon: "swap-horizontal-outline" },
  { key: "enquiries", label: "Contact enquiries", description: "Review support-enquiry status and member-provided context.", icon: "mail-outline" },
  { key: "chats", label: "Chat review", description: "Review protected-match headings for safety and dispute triage.", icon: "chatbubbles-outline" },
];

export function AdminScreen({ role }: Props) {
  const palette = useBridgeXAppearance();
  const { t } = useNativeLanguage();
  const [section, setSection] = useState<NativeAdminSection | null>(null);
  const [records, setRecords] = useState<NativeAdminRecord[]>([]);
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<NativeAdminRecord | null>(null);
  const [note, setNote] = useState("");
  const [rate, setRate] = useState("");
  const [loading, setLoading] = useState(false);
  const [busy, setBusy] = useState(false);
  const [page, setPage] = useState(0);
  const selectedSection = useMemo(() => sections.find(item => item.key === section) || null, [section]);
  const allowed = role === "admin" || role === "super_admin";
  const load = useCallback(async (target = 0, append = false) => {
    if (!section) return;
    setLoading(true);
    try {
      const rows = await loadNativeAdminSection(section, target);
      setRecords(current => append ? [...current, ...rows] : rows);
      setPage(target);
    } catch (error: any) { Alert.alert("BridgeX Admin", error?.message || "Could not load this operational section."); }
    finally { setLoading(false); }
  }, [section]);
  useEffect(() => { setSelected(null); setQuery(""); setNote(""); setRate(""); if (section) void load(0); }, [section, load]);
  const filtered = useMemo(() => {
    const term = query.trim().toLowerCase(); if (!term) return records;
    return records.filter(record => JSON.stringify(record).toLowerCase().includes(term));
  }, [records, query]);
  const act = async (label: string, operation: () => Promise<void>) => {
    setBusy(true);
    try { await operation(); Alert.alert("BridgeX Admin", `${label} completed.`); setSelected(null); setNote(""); await load(page); }
    catch (error: any) { Alert.alert("Action could not be completed", error?.message || "The server rejected this action. Confirm your administrator role and the record’s current state."); }
    finally { setBusy(false); }
  };
  if (!allowed) return <View style={[styles.denied, { backgroundColor: palette.background }]}><Ionicons name="shield-outline" size={36} color={palette.danger} /><Text style={[styles.deniedTitle, { color: palette.text }]}>Administrator access required</Text><Text style={[styles.deniedCopy, { color: palette.muted }]}>This protected control is visible only to users with an authorised BridgeX administrator role.</Text></View>;
  if (!section) return <FlatList style={{ backgroundColor: palette.background }} contentContainerStyle={styles.home} data={sections} keyExtractor={item => item.key} ListHeaderComponent={<><Text style={[styles.eyebrow, { color: palette.accent }]}>{role === "super_admin" ? "SUPER ADMIN CONTROL" : "BRIDGEX ADMINISTRATOR"}</Text><Text style={[styles.title, { color: palette.text }]}>Control panel</Text><Text style={[styles.copy, { color: palette.muted }]}>Open one separate operational page at a time. Server permissions, RLS, and protected RPCs remain the final authority for every action.</Text></>} renderItem={({ item }) => <Pressable onPress={() => setSection(item.key)} style={({ pressed }) => [styles.sectionCard, { backgroundColor: palette.surface, borderColor: palette.border }, pressed && styles.pressed]}><View style={[styles.sectionIcon, { backgroundColor: palette.primarySoft }]}><Ionicons name={item.icon} size={21} color={palette.primary} /></View><View style={styles.sectionBody}><Text style={[styles.sectionTitle, { color: palette.text }]}>{item.label}</Text><Text style={[styles.sectionCopy, { color: palette.muted }]}>{item.description}</Text></View><Ionicons name="chevron-forward" size={19} color={palette.muted} /></Pressable>} />;
  if (selected) return <ScrollView style={{ backgroundColor: palette.background }} contentContainerStyle={styles.detail}><Pressable onPress={() => setSelected(null)} style={styles.back}><Ionicons name="arrow-back" size={17} color={palette.primary} /><Text style={[styles.backText, { color: palette.primary }]}>{selectedSection?.label}</Text></Pressable><Text style={[styles.eyebrow, { color: palette.accent }]}>{selectedSection?.label.toUpperCase()}</Text><Text style={[styles.title, { color: palette.text }]}>{recordTitle(selected)}</Text><View style={[styles.detailCard, { backgroundColor: palette.surface, borderColor: palette.border }]}>{Object.entries(selected).filter(([key, value]) => value !== null && value !== undefined && !["proof_path", "storage_path", "evidence_paths"].includes(key)).slice(0, 16).map(([key, value]) => <View key={key} style={[styles.detailRow, { borderBottomColor: palette.border }]}><Text style={[styles.detailLabel, { color: palette.muted }]}>{key.replace(/_/g, " ")}</Text><Text selectable style={[styles.detailValue, { color: palette.text }]}>{formatValue(value)}</Text></View>)}</View><TextInput value={note} onChangeText={setNote} placeholder="Administrator note or required member-facing reason" placeholderTextColor={palette.muted} multiline style={[styles.note, { backgroundColor: palette.surface, borderColor: palette.border, color: palette.text }]} />{renderActions(section, selected, busy, rate, setRate, note, act, palette.primary, palette.danger)}</ScrollView>;
  return <View style={[styles.page, { backgroundColor: palette.background }]}><View style={styles.listHeader}><Pressable onPress={() => setSection(null)} style={styles.back}><Ionicons name="arrow-back" size={17} color={palette.primary} /><Text style={[styles.backText, { color: palette.primary }]}>Control panel</Text></Pressable><Text style={[styles.eyebrow, { color: palette.accent }]}>ADMINISTRATOR PAGE</Text><Text style={[styles.title, { color: palette.text }]}>{selectedSection?.label}</Text><Text style={[styles.copy, { color: palette.muted }]}>{selectedSection?.description}</Text><TextInput value={query} onChangeText={setQuery} placeholder="Search loaded records" placeholderTextColor={palette.muted} style={[styles.search, { backgroundColor: palette.surface, borderColor: palette.border, color: palette.text }]} /></View>{loading && !records.length ? <View style={styles.loader}><ActivityIndicator color={palette.primary} /></View> : <FlatList data={filtered} keyExtractor={item => item.id} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={[styles.empty, { color: palette.muted }]}>No records currently match this view.</Text>} renderItem={({ item }) => <Pressable onPress={() => setSelected(item)} style={({ pressed }) => [styles.record, { backgroundColor: palette.surface, borderColor: palette.border }, pressed && styles.pressed]}><View style={styles.recordBody}><Text style={[styles.recordTitle, { color: palette.text }]} numberOfLines={1}>{recordTitle(item)}</Text><Text style={[styles.recordDetail, { color: palette.muted }]} numberOfLines={2}>{recordDetail(item)}</Text></View><View style={[styles.status, { backgroundColor: palette.primarySoft }]}><Text style={[styles.statusText, { color: palette.primary }]}>{recordStatus(item)}</Text></View></Pressable>} ListFooterComponent={<Pressable onPress={() => void load(page + 1, true)} style={[styles.loadMore, { borderColor: palette.border }]}><Text style={[styles.backText, { color: palette.primary }]}>{loading ? "Loading…" : "Load more records"}</Text></Pressable>} />}</View>;
}

function renderActions(section: NativeAdminSection, record: NativeAdminRecord, busy: boolean, rate: string, setRate: (value: string) => void, note: string, act: (label: string, operation: () => Promise<void>) => void, primary: string, danger: string) {
  const button = (label: string, operation: () => Promise<void>, destructive = false) => <Pressable disabled={busy} key={label} onPress={() => void act(label, operation)} style={[styles.action, { backgroundColor: destructive ? danger : primary }, busy && styles.disabled]}>{busy ? <ActivityIndicator color="#fff" /> : <Text style={styles.actionText}>{label}</Text>}</Pressable>;
  if (section === "users") return <View>{record.suspended ? button("Restore member", () => moderateNativeMember(record.id, "restore")) : button("Restrict member", () => moderateNativeMember(record.id, "restrict", note), true)}</View>;
  if (section === "verification") return <View style={styles.actionRow}>{button("Approve verification", () => reviewNativeVerification(record.user_id, true))}{button("Reject verification", () => reviewNativeVerification(record.user_id, false), true)}</View>;
  if (section === "payments") return <View style={styles.actionRow}>{button("Verify payment", () => verifyNativeAdminPayment(record.id, "verified", note))}{button("Reject payment", () => verifyNativeAdminPayment(record.id, "rejected", note), true)}</View>;
  if (section === "payouts") return button("Mark payout sent", () => markNativeAdminPayoutSent(record.id, note, note));
  if (section === "orders") return <View style={styles.actionRow}>{button("Mark funded", () => updateNativeAdminOrder(record.id, "fund"))}{button("Mark in transit", () => updateNativeAdminOrder(record.id, "transit"))}{button("Mark delivered", () => updateNativeAdminOrder(record.id, "delivered"))}{button("Release escrow", () => updateNativeAdminOrder(record.id, "release"))}{button("Open dispute", () => updateNativeAdminOrder(record.id, "dispute"), true)}</View>;
  if (section === "reports") return <View style={styles.actionRow}>{button("Mark under review", () => updateNativeAdminReport(record.id, "under_review"))}{button("Close report", () => updateNativeAdminReport(record.id, "closed"), true)}</View>;
  if (section === "requests") return button(record.status === "closed" ? "Restore request" : "Pause request", () => moderateNativeAdminMarketplacePost("request", record.id, record.status === "closed" ? "restore" : "pause", note), record.status !== "closed");
  if (section === "listings") return button(record.status === "paused" ? "Restore listing" : "Pause listing", () => moderateNativeAdminMarketplacePost("listing", record.id, record.status === "paused" ? "restore" : "pause", note), record.status !== "paused");
  if (section === "exchange_rates") return <View><TextInput value={rate} onChangeText={setRate} keyboardType="decimal-pad" placeholder="New positive rate" style={styles.rateInput} />{button("Publish selected pair", () => saveNativeAdminExchangeRate(record.base_currency, record.quote_currency, Number(rate), new Date().toISOString()))}</View>;
  return <Text style={styles.readOnly}>This is a secure read-only operational review. Use the existing web detail page for private file viewing or support replies until the same protected API contract is exposed to mobile.</Text>;
}
function recordTitle(record: NativeAdminRecord) { return String(record.full_name || record.email || record.reference || record.title || record.subject || record.base_currency && `${record.base_currency} → ${record.quote_currency}` || record.sender_name && `${record.sender_name} ↔ ${record.traveler_name}` || record.document_type || `Record ${record.id.slice(0, 8)}`); }
function recordDetail(record: NativeAdminRecord) { return String(record.description || record.notes || record.message || record.institution_name || [record.current_city, record.current_country].filter(Boolean).join(", ") || [record.origin_city, record.destination_city].filter(Boolean).join(" → ") || "Open for secure details"); }
function recordStatus(record: NativeAdminRecord) { return String(record.status || record.verification_status || record.payout_status || record.escrow_status || record.suspended ? record.suspended ? "restricted" : record.status || record.verification_status || record.payout_status || record.escrow_status || "active" : "active").replace(/_/g, " "); }
function formatValue(value: any) { return typeof value === "object" ? JSON.stringify(value) : String(value); }

const styles = StyleSheet.create({ page: { flex: 1 }, home: { gap: 12, padding: 20, paddingBottom: 50 }, listHeader: { padding: 20, paddingBottom: 8 }, eyebrow: { fontSize: 10, fontWeight: "900", letterSpacing: 1.4 }, title: { fontFamily: "serif", fontSize: 29, fontWeight: "800", letterSpacing: -0.7, marginTop: 4 }, copy: { fontSize: 13, lineHeight: 20, marginTop: 7 }, sectionCard: { alignItems: "center", borderRadius: 18, borderWidth: 1, flexDirection: "row", gap: 12, padding: 15 }, sectionIcon: { alignItems: "center", borderRadius: 14, height: 44, justifyContent: "center", width: 44 }, sectionBody: { flex: 1 }, sectionTitle: { fontSize: 15, fontWeight: "900" }, sectionCopy: { fontSize: 11, lineHeight: 16, marginTop: 3 }, denied: { alignItems: "center", flex: 1, justifyContent: "center", padding: 30 }, deniedTitle: { fontSize: 18, fontWeight: "900", marginTop: 12 }, deniedCopy: { fontSize: 13, lineHeight: 20, marginTop: 7, textAlign: "center" }, back: { alignItems: "center", alignSelf: "flex-start", flexDirection: "row", gap: 5, marginBottom: 10 }, backText: { fontSize: 13, fontWeight: "900" }, search: { borderRadius: 13, borderWidth: 1, fontSize: 14, marginTop: 15, paddingHorizontal: 13, paddingVertical: 11 }, loader: { alignItems: "center", flex: 1, justifyContent: "center" }, list: { gap: 9, padding: 20, paddingTop: 8, paddingBottom: 48 }, record: { alignItems: "center", borderRadius: 15, borderWidth: 1, flexDirection: "row", gap: 9, padding: 13 }, recordBody: { flex: 1 }, recordTitle: { fontSize: 14, fontWeight: "900" }, recordDetail: { fontSize: 11, lineHeight: 16, marginTop: 3 }, status: { borderRadius: 14, maxWidth: 100, paddingHorizontal: 8, paddingVertical: 6 }, statusText: { fontSize: 9, fontWeight: "900", textTransform: "uppercase" }, empty: { paddingVertical: 40, textAlign: "center" }, loadMore: { alignItems: "center", borderRadius: 12, borderWidth: 1, marginTop: 8, paddingVertical: 12 }, detail: { gap: 12, padding: 20, paddingBottom: 50 }, detailCard: { borderRadius: 17, borderWidth: 1, paddingHorizontal: 14 }, detailRow: { borderBottomWidth: 1, paddingVertical: 10 }, detailLabel: { fontSize: 10, fontWeight: "900", textTransform: "uppercase" }, detailValue: { fontSize: 13, lineHeight: 18, marginTop: 3 }, note: { borderRadius: 13, borderWidth: 1, fontSize: 13, minHeight: 88, padding: 12, textAlignVertical: "top" }, action: { alignItems: "center", borderRadius: 13, justifyContent: "center", minHeight: 47, paddingHorizontal: 12, marginTop: 8 }, actionText: { color: "#fff", fontSize: 13, fontWeight: "900" }, actionRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, disabled: { opacity: 0.55 }, pressed: { opacity: 0.76, transform: [{ scale: 0.985 }] }, rateInput: { backgroundColor: "#fff", borderColor: "#c9c3df", borderRadius: 12, borderWidth: 1, marginTop: 8, padding: 12 }, readOnly: { color: "#657275", fontSize: 12, lineHeight: 19, marginTop: 4 } });
