import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { loadNativeAdminMembers, moderateNativeMember, type NativeAdminMember } from "../lib/api";

export function AdminScreen({ role }: { role?: string | null }) {
  const [members, setMembers] = useState<NativeAdminMember[]>([]);
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<NativeAdminMember | null>(null);
  const [reason, setReason] = useState("");
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { setMembers(await loadNativeAdminMembers()); } catch (error: any) { Alert.alert("BridgeX", error?.message || "Could not load members."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => members.filter(member => `${member.full_name || ""} ${member.email || ""} ${member.current_city || ""} ${member.current_country || ""}`.toLowerCase().includes(query.toLowerCase().trim())), [members, query]);
  const act = async (action: "restrict" | "restore") => { if (!selected) return; if (action === "restrict" && reason.trim().length < 5) return Alert.alert("Reason required", "Write a clear member-facing restriction explanation of at least five characters."); setBusy(true); try { await moderateNativeMember(selected.id, action, reason); Alert.alert("Member updated", action === "restrict" ? "The member was restricted and received the reason with an appeal path." : "The member restriction was removed and the member was notified."); setSelected(null); setReason(""); await load(); } catch (error: any) { Alert.alert("Could not update member", error?.message || "Please try again."); } finally { setBusy(false); } };
  if (role !== "admin" && role !== "super_admin") return <View style={styles.denied}><Text style={styles.deniedTitle}>Administrator access required</Text><Text style={styles.deniedCopy}>This native control is visible only to authorized BridgeX administrators.</Text></View>;
  if (selected) return <View style={styles.page}><Pressable onPress={() => setSelected(null)}><Text style={styles.back}>‹ Members</Text></Pressable><Text style={styles.eyebrow}>ADMINISTRATOR CONTROL</Text><Text style={styles.title}>{selected.full_name || selected.email || "BridgeX member"}</Text><View style={styles.card}><Info label="Email" value={selected.email || "Not available"} /><Info label="Role" value={selected.role || "member"} /><Info label="Verification" value={selected.verification_status || "not submitted"} /><Info label="Current location" value={[selected.current_city, selected.current_country].filter(Boolean).join(", ") || "Not provided"} /><Info label="Current status" value={selected.suspended ? "Restricted" : "Active"} /></View>{selected.suspended ? <><Text style={styles.reasonLabel}>Recorded restriction explanation</Text><Text style={styles.reasonCopy}>{selected.restriction_reason || "No reason recorded."}</Text><Pressable disabled={busy} onPress={() => void act("restore")} style={[styles.restore, busy && styles.disabled]}>{busy ? <ActivityIndicator color="#fff" /> : <Text style={styles.restoreText}>Restore member access</Text>}</Pressable></> : <><Text style={styles.reasonLabel}>Clear reason for the member</Text><TextInput value={reason} onChangeText={setReason} placeholder="Explain the restriction factually and include the appeal path." style={styles.reasonInput} multiline /><Pressable disabled={busy} onPress={() => void act("restrict")} style={[styles.restrict, busy && styles.disabled]}>{busy ? <ActivityIndicator color="#fff" /> : <Text style={styles.restrictText}>Restrict member</Text>}</Pressable></>}</View>;
  return <View style={styles.page}><Text style={styles.eyebrow}>{role === "super_admin" ? "SUPER ADMIN CONTROL" : "ADMINISTRATOR CONTROL"}</Text><Text style={styles.title}>Members</Text><Text style={styles.copy}>Search current members and use recorded reasons for any restriction action.</Text><TextInput value={query} onChangeText={setQuery} placeholder="Search name, email, city, or country" style={styles.search} />{loading ? <View style={styles.center}><ActivityIndicator color="#2d8d62" /></View> : <FlatList data={filtered} keyExtractor={item => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => <Pressable onPress={() => setSelected(item)} style={styles.member}><View style={styles.avatar}><Text style={styles.avatarText}>{(item.full_name || item.email || "M").slice(0, 1).toUpperCase()}</Text></View><View style={styles.memberCopy}><Text style={styles.memberName}>{item.full_name || "Unnamed member"}</Text><Text style={styles.memberDetail}>{item.email || "No email"} · {item.verification_status || "not submitted"}</Text></View><Text style={[styles.badge, item.suspended && styles.badgeRestricted]}>{item.suspended ? "Restricted" : item.role === "super_admin" ? "Super Admin" : item.role === "admin" ? "Admin" : "Active"}</Text></Pressable>} />}</View>;
}

function Info({ label, value }: { label: string; value: string }) { return <View style={styles.info}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ page: { backgroundColor: "#f7f5ef", flex: 1, padding: 20 }, denied: { alignItems: "center", backgroundColor: "#f7f5ef", flex: 1, justifyContent: "center", padding: 30 }, deniedTitle: { color: "#29373a", fontSize: 18, fontWeight: "900" }, deniedCopy: { color: "#697779", fontSize: 13, lineHeight: 20, marginTop: 7, textAlign: "center" }, eyebrow: { color: "#aa7612", fontSize: 10, fontWeight: "900", letterSpacing: 1.5 }, title: { color: "#172126", fontFamily: "serif", fontSize: 30, fontWeight: "800", letterSpacing: -0.9, marginTop: 3 }, copy: { color: "#687679", fontSize: 13, lineHeight: 19, marginTop: 3 }, search: { backgroundColor: "#fff", borderColor: "#dce4db", borderRadius: 12, borderWidth: 1, marginTop: 16, paddingHorizontal: 13, paddingVertical: 12 }, center: { alignItems: "center", flex: 1, justifyContent: "center" }, list: { gap: 9, paddingTop: 16 }, member: { alignItems: "center", backgroundColor: "#fff", borderColor: "#dce4db", borderRadius: 14, borderWidth: 1, flexDirection: "row", gap: 10, padding: 13 }, avatar: { alignItems: "center", backgroundColor: "#e7f4ea", borderRadius: 19, height: 38, justifyContent: "center", width: 38 }, avatarText: { color: "#176447", fontSize: 14, fontWeight: "900" }, memberCopy: { flex: 1 }, memberName: { color: "#29373a", fontSize: 14, fontWeight: "900" }, memberDetail: { color: "#6c797c", fontSize: 11, marginTop: 3 }, badge: { backgroundColor: "#e7f4ea", borderRadius: 16, color: "#176447", fontSize: 9, fontWeight: "900", overflow: "hidden", paddingHorizontal: 8, paddingVertical: 5, textTransform: "uppercase" }, badgeRestricted: { backgroundColor: "#fff0ea", color: "#924638" }, back: { color: "#176447", fontSize: 14, fontWeight: "900", marginBottom: 7 }, card: { backgroundColor: "#fff", borderColor: "#dce4db", borderRadius: 16, borderWidth: 1, marginTop: 18, padding: 15 }, info: { borderBottomColor: "#edf0eb", borderBottomWidth: 1, paddingVertical: 10 }, infoLabel: { color: "#6c797c", fontSize: 10, fontWeight: "900", textTransform: "uppercase" }, infoValue: { color: "#29373a", fontSize: 13, fontWeight: "800", marginTop: 3 }, reasonLabel: { color: "#29373a", fontSize: 14, fontWeight: "900", marginTop: 18 }, reasonCopy: { color: "#677477", fontSize: 13, lineHeight: 20, marginTop: 6 }, reasonInput: { backgroundColor: "#fff", borderColor: "#dfb4a4", borderRadius: 13, borderWidth: 1, color: "#29373a", marginTop: 8, minHeight: 118, padding: 13, textAlignVertical: "top" }, restrict: { alignItems: "center", backgroundColor: "#9a493a", borderRadius: 13, marginTop: 12, paddingVertical: 14 }, restrictText: { color: "#fff", fontSize: 14, fontWeight: "900" }, restore: { alignItems: "center", backgroundColor: "#176447", borderRadius: 13, marginTop: 18, paddingVertical: 14 }, restoreText: { color: "#fff", fontSize: 14, fontWeight: "900" }, disabled: { opacity: 0.55 } });
