import * as WebBrowser from "expo-web-browser";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import type { NativeInfoSection } from "../types";

type Content = { eyebrow: string; title: string; lead: string; sections: Array<{ title: string; body: string }> };
const site = "https://bridgex.abdullahbinfahad.info";
const content: Record<NativeInfoSection, Content> = {
  about: { eyebrow: "ABOUT BRIDGEX", title: "A global goods-carrying marketplace", lead: "BridgeX helps senders and travellers or carriers discover lawful, clearly described delivery opportunities across domestic and international routes.", sections: [{ title: "Member-to-member service", body: "BridgeX provides tools for posting, matching, protected communication, verification, order tracking, payment-status review, and safety reporting. Members remain responsible for the goods they send or agree to carry." }, { title: "Global by design", body: "A request or carry listing can use any origin and destination. Domestic same-country services and cross-border routes are supported when members accurately describe the route, timing, item, and handling requirements." }] },
  how_it_works: { eyebrow: "HOW IT WORKS", title: "Post. Match. Carry safely.", lead: "BridgeX follows a clear protected workflow built around complete information and mutual confirmation.", sections: [{ title: "1. Post accurately", body: "A sender creates an item request or a traveller lists real capacity, route, timing, categories, quantities, and handling needs." }, { title: "2. Respond responsibly", body: "Travellers make offers on requests. Senders show interest in available carry space. Both must supply accurate protected contact and delivery details before a match can progress." }, { title: "3. Match and complete", body: "After the approved payment-status and matching steps, the participants can communicate in protected messages, update milestones, confirm delivery, and complete eligible reviews." }] },
  safety: { eyebrow: "SAFETY", title: "Put lawful, honest delivery first", lead: "Trust depends on accurate information, respectful communication, and compliance with the laws and carrier rules that apply to each route.", sections: [{ title: "Before posting or responding", body: "Use precise item descriptions, truthful declared value and purpose where required, realistic timing, and any handling needs. Do not post illegal, restricted, dangerous, concealed, or inaccurately described items." }, { title: "Choose carefully", body: "Review member verification and public ratings as context, not as a guarantee. Confirm the route, capacity, delivery deadline, and lawful transport conditions before you accept an offer or interest." }, { title: "Report concerns", body: "Use the BridgeX safety-report and support routes for suspected fraud, threats, inaccurate declarations, prohibited goods, or unsafe conduct. BridgeX may restrict accounts or cooperate with lawful requests where required." }] },
  contact: { eyebrow: "CONTACT", title: "BridgeX support", lead: "Use the BridgeX contact route for support, account-access concerns, privacy requests, moderation appeals, or factual safety reports.", sections: [{ title: "Secure contact route", body: "The website contact form is available to guests and members. When signed in, its support updates can also appear in your protected BridgeX updates and messages." }, { title: "Protect your information", body: "Do not send passwords or unneeded identity numbers in a message. Use the dedicated private verification process when a document is required." }] },
  downloads: { eyebrow: "DOWNLOADS", title: "BridgeX releases", lead: "Use official BridgeX download destinations and keep Android installations updated when a supported version is published.", sections: [{ title: "Android", body: "The current signed BridgeX Android APK is provided through the official BridgeX website footer. Google Play distribution uses the signed Android App Bundle when the Play release is approved." }, { title: "Other platforms", body: "The website also lists available Windows, macOS, and HarmonyOS release information. Do not install software from unofficial sources claiming to be BridgeX." }] },
  legal: { eyebrow: "LEGAL", title: "Members remain responsible", lead: "BridgeX is a marketplace service that connects members; it does not replace customs, carrier, consumer-protection, insurance, or legal advice.", sections: [{ title: "Transport and customs", body: "Members must check and follow applicable import, export, customs, airline, train, cargo, safety, and local laws. Duties, fees, declarations, and carrier rules can apply." }, { title: "Accurate declarations", body: "A sender must provide truthful item details, declared value, purpose, commercial-use information, and lawful handling requirements. A traveller may refuse an unsafe, prohibited, concealed, or materially mismatched handoff without penalty." }] },
  terms: { eyebrow: "TERMS", title: "BridgeX member terms", lead: "The full current terms are published on the BridgeX website and are acknowledged at key posting, response, and acceptance stages.", sections: [{ title: "Core rules", body: "Use truthful information, communicate respectfully, protect account access, respect privacy, comply with laws and platform restrictions, and only accept work you can realistically complete." }, { title: "Enforcement", body: "BridgeX may pause or remove posts, restrict accounts, cancel workflow access, retain required records, or make reports where needed to protect members, the platform, or comply with law." }] },
  privacy: { eyebrow: "PRIVACY", title: "Private data and access", lead: "BridgeX limits private contact and verification data to the purpose for which it was provided, subject to lawful safety, support, and compliance needs.", sections: [{ title: "What stays private", body: "Exact addresses, phone numbers, identification documents, private payment proof, and other sensitive account information are not part of public marketplace profiles or post cards." }, { title: "Protected sharing", body: "Counterpart contact details are shared only through an eligible protected match. Authorized administrators may access necessary records for support, disputes, safety review, or legal obligations." }] },
};

export function InfoScreen({ section, onBack }: { section: NativeInfoSection; onBack: () => void }) {
  const page = content[section];
  const openWebsite = () => void WebBrowser.openBrowserAsync(`${site}/${section === "how_it_works" ? "how-it-works" : section}`);
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><Pressable onPress={onBack}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.eyebrow}>{page.eyebrow}</Text><Text style={styles.title}>{page.title}</Text><Text style={styles.lead}>{page.lead}</Text>{page.sections.map(item => <View key={item.title} style={styles.card}><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.cardBody}>{item.body}</Text></View>)}<Pressable onPress={openWebsite} style={({ pressed }) => [styles.action, pressed && styles.pressed]}><Text style={styles.actionText}>Open current website page</Text></Pressable></ScrollView>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#f7f5ef" }, content: { gap: 14, padding: 20, paddingBottom: 48 }, back: { color: "#176447", fontSize: 14, fontWeight: "900" }, eyebrow: { color: "#2d8d62", fontSize: 10, fontWeight: "900", letterSpacing: 1.5, marginTop: 4 }, title: { color: "#172126", fontFamily: "serif", fontSize: 31, fontWeight: "800", letterSpacing: -1, lineHeight: 36 }, lead: { color: "#566668", fontSize: 14, lineHeight: 21 }, card: { backgroundColor: "#fff", borderColor: "#dfe5dd", borderRadius: 17, borderWidth: 1, padding: 16 }, cardTitle: { color: "#263438", fontSize: 15, fontWeight: "900" }, cardBody: { color: "#526164", fontSize: 13, lineHeight: 20, marginTop: 6 }, action: { alignItems: "center", backgroundColor: "#172126", borderRadius: 14, marginTop: 4, paddingVertical: 14 }, actionText: { color: "#fff", fontSize: 14, fontWeight: "900" }, pressed: { opacity: 0.76, transform: [{ scale: 0.985 }] } });
