import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SUPPORTED_CURRENCIES } from "../lib/constants";
import { deleteNativeManagedPost, loadNativeManagedPosts, updateNativeManagedPost, type NativeManagedPost } from "../lib/api";

export function ManagePostsScreen({ userId, onBack }: { userId: string; onBack: () => void }) {
  const [posts, setPosts] = useState<NativeManagedPost[]>([]);
  const [selected, setSelected] = useState<NativeManagedPost | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { setPosts(await loadNativeManagedPosts(userId)); } catch (error: any) { Alert.alert("BridgeX", error?.message || "Could not load your posts."); } finally { setLoading(false); } }, [userId]);
  useEffect(() => { void load(); }, [load]);
  const change = (key: keyof NativeManagedPost, value: string) => setSelected(current => current ? { ...current, [key]: value } : current);
  const save = async () => { if (!selected) return; setBusy(true); try { await updateNativeManagedPost(userId, selected); setSelected(null); await load(); Alert.alert("Post updated", "Your open post was updated."); } catch (error: any) { Alert.alert("Could not update post", error?.message || "Only open posts can be edited."); } finally { setBusy(false); } };
  const remove = (post: NativeManagedPost) => Alert.alert("Delete open post?", "Open posts can be removed. Protected matched records are retained and cannot be deleted here.", [{ text: "Keep", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => void (async () => { setBusy(true); try { await deleteNativeManagedPost(userId, post); await load(); } catch (error: any) { Alert.alert("Could not delete post", error?.message || "Only eligible open posts can be deleted."); } finally { setBusy(false); } })() }]);
  if (selected) return <ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Pressable onPress={() => setSelected(null)}><Text style={styles.back}>‹ Manage posts</Text></Pressable><Text style={styles.eyebrow}>OPEN POST</Text><Text style={styles.title}>Edit details</Text><Text style={styles.copy}>Only open posts can change here. Accepted or protected records remain governed by the protected order workflow.</Text>{selected.kind === "request" ? <Field label="Post title"><TextInput value={selected.title} onChangeText={value => change("title", value)} style={styles.input} /></Field> : <View style={styles.readonly}><Text style={styles.readonlyLabel}>Listing</Text><Text style={styles.readonlyText}>{selected.title}</Text></View>}<Field label="Details / notes"><TextInput value={selected.description} onChangeText={value => change("description", value)} style={[styles.input, styles.long]} multiline /></Field><View style={styles.grid}><Field label={selected.kind === "request" ? "Budget" : "Price"}><TextInput value={selected.amount} onChangeText={value => change("amount", value)} keyboardType="decimal-pad" style={styles.input} /></Field><Field label="Weight / capacity (kg)"><TextInput value={selected.weight} onChangeText={value => change("weight", value)} keyboardType="decimal-pad" style={styles.input} /></Field></View><Text style={styles.label}>Currency</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.currencyChoices}>{SUPPORTED_CURRENCIES.map(currency => <Pressable key={currency} onPress={() => change("currency", currency)} style={[styles.currency, selected.currency === currency && styles.currencyActive]}><Text style={[styles.currencyText, selected.currency === currency && styles.currencyTextActive]}>{currency}</Text></Pressable>)}</ScrollView>{selected.kind === "listing" ? <Field label="Departure date and time"><TextInput value={selected.departure ? new Date(selected.departure).toISOString().slice(0, 16) : ""} onChangeText={value => change("departure", value)} placeholder="YYYY-MM-DDTHH:MM" placeholderTextColor="#657377" style={styles.input} /></Field> : null}<Pressable disabled={busy} onPress={() => void save()} style={[styles.primary, busy && styles.disabled]}>{busy ? <ActivityIndicator color="#fff" /> : <Text style={styles.primaryText}>Save open post</Text>}</Pressable></ScrollView>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><Pressable onPress={onBack}><Text style={styles.back}>‹ Workspace</Text></Pressable><Text style={styles.eyebrow}>MY PUBLISHING CONTROLS</Text><Text style={styles.title}>Manage posts</Text><Text style={styles.copy}>Open a post to review, edit, or delete it. Once a response becomes protected, the record is managed through the order and payment workflow.</Text>{loading ? <View style={styles.loading}><ActivityIndicator color="#2d8d62" /></View> : posts.length ? posts.map(post => <View key={`${post.kind}-${post.id}`} style={styles.card}><Text style={styles.tag}>{post.kind === "request" ? "I NEED TO SEND" : "CARRY SPACE"} · {post.status.replace(/_/g, " ")}</Text><Text style={styles.cardTitle}>{post.title}</Text><Text style={styles.cardCopy}>{post.origin} → {post.destination}</Text><Text style={styles.cardCopy}>{post.weight} kg · {post.currency} {post.amount}</Text>{post.status === "open" ? <View style={styles.actions}><Pressable onPress={() => setSelected(post)} style={styles.secondary}><Text style={styles.secondaryText}>Edit post</Text></Pressable><Pressable disabled={busy} onPress={() => remove(post)} style={styles.delete}><Text style={styles.deleteText}>Delete</Text></Pressable></View> : <Text style={styles.locked}>Protected or closed posts are retained in their deal history.</Text>}</View>) : <View style={styles.empty}><Text style={styles.emptyTitle}>No published posts yet</Text><Text style={styles.emptyCopy}>Your item requests and carry-space listings will appear here after publishing.</Text></View>}</ScrollView>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text>{children}</View>; }
const styles = StyleSheet.create({ page: { backgroundColor: "#f7f5ef", flex: 1 }, content: { gap: 14, padding: 20, paddingBottom: 42 }, back: { color: "#176447", fontSize: 14, fontWeight: "900" }, eyebrow: { color: "#2d8d62", fontSize: 10, fontWeight: "900", letterSpacing: 1.4, marginTop: 5 }, title: { color: "#172126", fontFamily: "serif", fontSize: 30, fontWeight: "800", marginTop: 2 }, copy: { color: "#687679", fontSize: 13, lineHeight: 19 }, loading: { alignItems: "center", paddingVertical: 30 }, card: { backgroundColor: "#fff", borderColor: "#dbe2da", borderRadius: 16, borderWidth: 1, padding: 15 }, tag: { color: "#176447", fontSize: 10, fontWeight: "900", textTransform: "uppercase" }, cardTitle: { color: "#263438", fontSize: 16, fontWeight: "900", marginTop: 6 }, cardCopy: { color: "#687679", fontSize: 12, lineHeight: 18, marginTop: 4 }, actions: { flexDirection: "row", gap: 8, marginTop: 13 }, secondary: { backgroundColor: "#edf7ee", borderRadius: 9, paddingHorizontal: 12, paddingVertical: 9 }, secondaryText: { color: "#176447", fontSize: 12, fontWeight: "900" }, delete: { backgroundColor: "#fff2ee", borderRadius: 9, paddingHorizontal: 12, paddingVertical: 9 }, deleteText: { color: "#a24135", fontSize: 12, fontWeight: "900" }, locked: { color: "#687679", fontSize: 11, fontWeight: "800", marginTop: 11 }, empty: { alignItems: "center", backgroundColor: "#fff", borderColor: "#dbe2da", borderRadius: 16, borderStyle: "dashed", borderWidth: 1, padding: 28 }, emptyTitle: { color: "#263438", fontSize: 16, fontWeight: "900" }, emptyCopy: { color: "#687679", fontSize: 12, lineHeight: 18, marginTop: 6, textAlign: "center" }, field: { gap: 7 }, label: { color: "#29373a", fontSize: 13, fontWeight: "900" }, input: { backgroundColor: "#fff", borderColor: "#dbe2da", borderRadius: 12, borderWidth: 1, color: "#172126", fontSize: 14, paddingHorizontal: 13, paddingVertical: 12 }, long: { minHeight: 105, textAlignVertical: "top" }, grid: { flexDirection: "row", gap: 10 }, readonly: { backgroundColor: "#edf7ee", borderRadius: 12, padding: 13 }, readonlyLabel: { color: "#61766a", fontSize: 10, fontWeight: "900", textTransform: "uppercase" }, readonlyText: { color: "#263438", fontSize: 14, fontWeight: "900", marginTop: 3 }, currencyChoices: { gap: 7, paddingBottom: 2 }, currency: { backgroundColor: "#fff", borderColor: "#dbe2da", borderRadius: 18, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 8 }, currencyActive: { backgroundColor: "#176447", borderColor: "#176447" }, currencyText: { color: "#536164", fontSize: 11, fontWeight: "900" }, currencyTextActive: { color: "#fff" }, primary: { alignItems: "center", backgroundColor: "#176447", borderRadius: 14, justifyContent: "center", minHeight: 52, marginTop: 8 }, primaryText: { color: "#fff", fontSize: 15, fontWeight: "900" }, disabled: { opacity: 0.55 } });
