import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Image, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from "react-native";
import { loadMarketplace } from "../lib/api";
import { supabase } from "../lib/supabase";
import type { MarketplacePost, MarketplaceTab } from "../types";

type Props = { onOpenPost: (post: MarketplacePost) => void; };

function publicMedia(path?: string) { return path ? supabase.storage.from("request-media").getPublicUrl(path).data.publicUrl : undefined; }

export function MarketplaceScreen({ onOpenPost }: Props) {
  const [tab, setTab] = useState<MarketplaceTab>("requests");
  const [posts, setPosts] = useState<MarketplacePost[]>([]);
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState("");
  const load = useCallback(async (refresh = false) => {
    refresh ? setRefreshing(true) : setLoading(true);
    try { setError(""); setPosts(await loadMarketplace(tab)); }
    catch (failure: any) { setError(failure?.message || "BridgeX could not load posts right now."); }
    finally { setLoading(false); setRefreshing(false); }
  }, [tab]);
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => posts.filter(post => `${post.title} ${post.route} ${post.category || ""}`.toLowerCase().includes(query.toLowerCase().trim())), [posts, query]);
  return <View style={styles.page}><View style={styles.switcher}><Pressable onPress={() => setTab("requests")} style={[styles.switch, tab === "requests" && styles.switchActive]}><Text style={[styles.switchText, tab === "requests" && styles.switchTextActive]}>Requests</Text></Pressable><Pressable onPress={() => setTab("carry")} style={[styles.switch, tab === "carry" && styles.switchActive]}><Text style={[styles.switchText, tab === "carry" && styles.switchTextActive]}>Carry space</Text></Pressable></View><TextInput value={query} onChangeText={setQuery} placeholder="Search product, origin, destination, or route" placeholderTextColor="#657377" selectionColor="#2d8d62" style={styles.search} autoCorrect={false} /><FlatList data={filtered} keyExtractor={post => post.id} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor="#2d8d62" />} contentContainerStyle={styles.list} ListHeaderComponent={loading ? <View style={styles.center}><ActivityIndicator color="#2d8d62" /></View> : error ? <View style={styles.error}><Text style={styles.errorText}>{error}</Text><Pressable onPress={() => void load()}><Text style={styles.retry}>Try again</Text></Pressable></View> : <Text style={styles.summary}>{filtered.length} live {tab === "requests" ? "requests" : "carry listings"}</Text>} ListEmptyComponent={!loading ? <View style={styles.empty}><Text style={styles.emptyTitle}>No live posts found</Text><Text style={styles.emptyCopy}>Try a different search or check back after new members publish.</Text></View> : null} renderItem={({ item }) => <PostCard post={item} onPress={() => onOpenPost(item)} />} /> </View>;
}

function PostCard({ post, onPress }: { post: MarketplacePost; onPress: () => void }) {
  const media = publicMedia(post.mediaPaths[0]);
  return <Pressable onPress={onPress} style={({ pressed }) => [styles.card, pressed && styles.pressed]}>{media ? <Image source={{ uri: media }} style={styles.image} resizeMode="cover" /> : <View style={styles.mediaFallback}><Text style={styles.fallbackIcon}>⌑</Text></View>}<View style={styles.cardBody}><View style={styles.tagRow}><Text style={styles.tag}>{post.kind === "requests" ? "ITEM REQUEST" : "CARRY SPACE"}</Text><Text style={styles.live}>LIVE</Text></View><Text style={styles.cardTitle} numberOfLines={2}>{post.title}</Text>{post.category ? <Text style={styles.category} numberOfLines={1}>{post.category}</Text> : null}<Text style={styles.route} numberOfLines={2}>{post.route}</Text><View style={styles.details}><Text style={styles.detail}>{post.weight}</Text><Text style={styles.detail}>{post.currency} {post.price.toLocaleString()}</Text></View><View style={styles.open}><Text style={styles.openText}>View details</Text><Text style={styles.arrow}>›</Text></View></View></Pressable>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#f7f5ef" }, switcher: { alignSelf: "flex-start", backgroundColor: "#e9e5d9", borderRadius: 12, flexDirection: "row", marginHorizontal: 20, marginTop: 3, padding: 4 }, switch: { borderRadius: 9, paddingHorizontal: 14, paddingVertical: 9 }, switchActive: { backgroundColor: "#172126" }, switchText: { color: "#5d696c", fontSize: 12, fontWeight: "800" }, switchTextActive: { color: "#fff" }, search: { backgroundColor: "#ffffff", borderColor: "#b6c3b7", borderRadius: 12, borderWidth: 1, color: "#172126", fontSize: 14, marginHorizontal: 20, marginTop: 12, paddingHorizontal: 13, paddingVertical: 12 }, list: { gap: 12, padding: 20, paddingBottom: 104 }, summary: { color: "#667274", fontSize: 12, fontWeight: "800", marginBottom: 2 }, center: { alignItems: "center", paddingVertical: 30 }, card: { backgroundColor: "#fff", borderColor: "#dee4dc", borderRadius: 18, borderWidth: 1, overflow: "hidden" }, image: { backgroundColor: "#eef4ef", height: 152, width: "100%" }, mediaFallback: { alignItems: "center", backgroundColor: "#e7f1e8", height: 112, justifyContent: "center" }, fallbackIcon: { color: "#2d8d62", fontSize: 34 }, cardBody: { padding: 15 }, tagRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, tag: { backgroundColor: "#e7f4ea", borderRadius: 30, color: "#23784f", fontSize: 9, fontWeight: "900", letterSpacing: 0.8, overflow: "hidden", paddingHorizontal: 8, paddingVertical: 5 }, live: { color: "#738082", fontSize: 10, fontWeight: "800" }, cardTitle: { color: "#172126", fontSize: 17, fontWeight: "800", letterSpacing: -0.25, marginTop: 12 }, category: { color: "#86600d", fontSize: 11, fontWeight: "800", marginTop: 4 }, route: { color: "#506064", fontSize: 13, lineHeight: 19, marginTop: 10 }, details: { flexDirection: "row", gap: 13, marginTop: 11 }, detail: { color: "#536164", fontSize: 12, fontWeight: "800" }, open: { alignItems: "center", borderTopColor: "#e8ece7", borderTopWidth: 1, flexDirection: "row", justifyContent: "space-between", marginTop: 13, paddingTop: 11 }, openText: { color: "#176447", fontSize: 13, fontWeight: "900" }, arrow: { color: "#176447", fontSize: 23, fontWeight: "500", lineHeight: 20 }, error: { alignItems: "center", backgroundColor: "#f7e8e5", borderRadius: 14, padding: 14 }, errorText: { color: "#924638", fontSize: 13, fontWeight: "700", textAlign: "center" }, retry: { color: "#176447", fontSize: 13, fontWeight: "900", marginTop: 8 }, empty: { alignItems: "center", paddingHorizontal: 30, paddingVertical: 48 }, emptyTitle: { color: "#172126", fontSize: 18, fontWeight: "900" }, emptyCopy: { color: "#677477", fontSize: 13, lineHeight: 20, marginTop: 7, textAlign: "center" }, pressed: { opacity: 0.8, transform: [{ scale: 0.99 }] } });
