import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { loadMarketplace, loadNativeMemberReviews, type NativeMemberReview } from "../lib/api";
import type { MarketplacePost } from "../types";

type Props = { ownerId: string; name?: string | null; verified?: boolean; rating?: number; reviewCount?: number; onBack: () => void; onOpenPost: (post: MarketplacePost) => void };

export function MemberProfileScreen({ ownerId, name, verified, rating = 0, reviewCount = 0, onBack, onOpenPost }: Props) {
  const [posts, setPosts] = useState<MarketplacePost[]>([]);
  const [reviews, setReviews] = useState<NativeMemberReview[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { void Promise.all([loadMarketplace("requests", 0, 80), loadMarketplace("carry", 0, 80), loadNativeMemberReviews(ownerId)]).then(([requests, listings, feedback]) => { setPosts([...requests, ...listings].filter(post => post.ownerId === ownerId)); setReviews(feedback); }).finally(() => setLoading(false)); }, [ownerId]);
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><Pressable onPress={onBack}><Text style={styles.back}>‹ Back</Text></Pressable><View style={styles.identity}><View style={styles.avatar}><Text style={styles.avatarText}>{String(name || "B").slice(0, 1).toUpperCase()}</Text></View><View style={styles.identityCopy}><Text style={styles.name}>{name || "BridgeX member"}</Text><Text style={[styles.badge, verified ? styles.verified : styles.pending]}>{verified ? "Verified" : "Not verified"}</Text><Text style={styles.rating}>★ {rating.toFixed(1)} ({reviewCount})</Text></View></View><Text style={styles.description}>Public BridgeX posts from this member. Contact details, exact addresses, documents, and other private account data are never shown here.</Text><Text style={styles.heading}>Completed-service reviews</Text>{loading ? <View style={styles.loading}><ActivityIndicator color="#2d8d62" /></View> : reviews.length ? reviews.map(review => <View key={review.id} style={styles.review}><Text style={styles.reviewRating}>★ {Number(review.rating).toFixed(1)} / 5</Text><Text style={styles.reviewComment}>{review.comment}</Text><Text style={styles.reviewDate}>Completed-order feedback · {new Date(review.created_at).toLocaleDateString()}</Text></View>) : <View style={styles.reviewEmpty}><Text style={styles.emptyCopy}>No completed-service comments yet.</Text></View>}<Text style={styles.heading}>Current public posts</Text>{loading ? <View style={styles.loading}><ActivityIndicator color="#2d8d62" /></View> : posts.length ? posts.map(post => <Pressable key={`${post.kind}:${post.id}`} onPress={() => onOpenPost(post)} style={({ pressed }) => [styles.post, pressed && styles.pressed]}><Text style={styles.postType}>{post.kind === "requests" ? "ITEM REQUEST" : "CARRY SPACE"}</Text><Text style={styles.postTitle}>{post.title}</Text><Text style={styles.route}>{post.route}</Text><Text style={styles.meta}>{post.weight} · {post.currency} {post.price.toLocaleString()}</Text></Pressable>) : <View style={styles.empty}><Text style={styles.emptyTitle}>No current public posts</Text><Text style={styles.emptyCopy}>This member has no open requests or carry listings visible right now.</Text></View>}</ScrollView>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#f7f5ef" }, content: { gap: 14, padding: 20, paddingBottom: 44 }, back: { color: "#176447", fontSize: 14, fontWeight: "900" }, identity: { alignItems: "center", backgroundColor: "#172126", borderRadius: 20, flexDirection: "row", gap: 14, padding: 18 }, avatar: { alignItems: "center", backgroundColor: "#a8e5c3", borderRadius: 28, height: 56, justifyContent: "center", width: 56 }, avatarText: { color: "#172126", fontSize: 23, fontWeight: "900" }, identityCopy: { gap: 3 }, name: { color: "#fff", fontSize: 20, fontWeight: "900" }, badge: { alignSelf: "flex-start", borderRadius: 12, fontSize: 11, fontWeight: "900", overflow: "hidden", paddingHorizontal: 8, paddingVertical: 4 }, verified: { backgroundColor: "#dff4e5", color: "#176447" }, pending: { backgroundColor: "#fff0bf", color: "#765b1a" }, rating: { color: "#f5c24d", fontSize: 12, fontWeight: "900" }, description: { color: "#5f6f70", fontSize: 13, lineHeight: 20 }, heading: { color: "#172126", fontFamily: "serif", fontSize: 25, fontWeight: "800", marginTop: 6 }, loading: { alignItems: "center", paddingVertical: 28 }, review: { backgroundColor: "#fff", borderColor: "#dce5db", borderRadius: 16, borderWidth: 1, padding: 15 }, reviewRating: { color: "#795b08", fontSize: 13, fontWeight: "900" }, reviewComment: { color: "#4d5d60", fontSize: 13, lineHeight: 20, marginTop: 7 }, reviewDate: { color: "#778486", fontSize: 10, marginTop: 9 }, reviewEmpty: { backgroundColor: "#fff", borderColor: "#dce5db", borderRadius: 16, borderWidth: 1, padding: 16 }, post: { backgroundColor: "#fff", borderColor: "#dce5db", borderRadius: 16, borderWidth: 1, padding: 15 }, postType: { color: "#2d8d62", fontSize: 10, fontWeight: "900", letterSpacing: 1 }, postTitle: { color: "#172126", fontSize: 16, fontWeight: "900", marginTop: 7 }, route: { color: "#506064", fontSize: 12, lineHeight: 18, marginTop: 7 }, meta: { color: "#176447", fontSize: 12, fontWeight: "800", marginTop: 6 }, empty: { alignItems: "center", backgroundColor: "#fff", borderColor: "#dce5db", borderRadius: 18, borderWidth: 1, padding: 24 }, emptyTitle: { color: "#263438", fontSize: 16, fontWeight: "900" }, emptyCopy: { color: "#657376", fontSize: 13, lineHeight: 19, marginTop: 6, textAlign: "center" }, pressed: { opacity: 0.76, transform: [{ scale: 0.985 }] } });
