import Ionicons from "@expo/vector-icons/Ionicons";
import * as Haptics from "expo-haptics";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import type { ReactNode } from "react";
import type { NativeInfoSection } from "../types";
import { useBridgeXAppearance } from "../lib/appearance";
import { useNativeLanguage } from "../lib/i18n";

type Badges = { profile: number; workspace: number; messages: number; updates: number; payments: number; admin: number };
type Props = { signedIn: boolean; role?: string | null; badges: Badges; onProfile: () => void; onWorkspace: () => void; onMessages: () => void; onUpdates: () => void; onPayments: () => void; onAdmin: () => void; onInfo: (section: NativeInfoSection) => void };

export function MoreScreen({ signedIn, role, badges, onProfile, onWorkspace, onMessages, onUpdates, onPayments, onAdmin, onInfo }: Props) {
  const palette = useBridgeXAppearance();
  const { t } = useNativeLanguage();
  const tap = (callback: () => void) => { void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); callback(); };
  const authorized = role === "admin" || role === "super_admin";
  return <ScrollView style={[styles.page, { backgroundColor: palette.background }]} contentContainerStyle={styles.content}>
    <Text style={[styles.eyebrow, { color: palette.accent }]}>BRIDGEX</Text><Text style={[styles.title, { color: palette.text }]}>{t("more")}</Text><Text style={[styles.copy, { color: palette.muted }]}>Account settings, support, downloads, safety, and legal information in one place.</Text>
    {signedIn ? <Section title="Your account" palette={palette}>
      <Item icon="person-circle-outline" title={t("profile")} copy="Private contact details, language, currency, and identity review." badge={badges.profile} palette={palette} onPress={() => tap(onProfile)} />
      <Item icon="briefcase-outline" title={t("workspace")} copy="Posts, offers, protected orders, and account activity." badge={badges.workspace} palette={palette} onPress={() => tap(onWorkspace)} />
      <Item icon="chatbubbles-outline" title={t("messages")} copy="Protected conversations and member support." badge={badges.messages} palette={palette} onPress={() => tap(onMessages)} />
      <Item icon="notifications-outline" title={t("updates")} copy="Account, order, verification, and service updates." badge={badges.updates} palette={palette} onPress={() => tap(onUpdates)} />
      <Item icon="card-outline" title={t("payments")} copy="Protected payment records and traveler payouts." badge={badges.payments} palette={palette} onPress={() => tap(onPayments)} />
      {authorized ? <Item icon="shield-checkmark-outline" title={role === "super_admin" ? "Super Admin control" : "Administrator control"} copy="Member management and authorized safety controls." badge={badges.admin} palette={palette} onPress={() => tap(onAdmin)} emphasis /> : null}
    </Section> : <View style={[styles.guest, { backgroundColor: palette.primarySoft, borderColor: palette.border }]}><Text style={[styles.guestTitle, { color: palette.accent }]}>Browsing as a guest</Text><Text style={[styles.guestCopy, { color: palette.muted }]}>Sign in to manage a profile, post, respond, use protected messaging, or open private payment records.</Text></View>}
    <Section title="Discover BridgeX" palette={palette}><Item icon="sparkles-outline" title="About us" copy="The purpose and member-to-member model behind BridgeX." palette={palette} onPress={() => tap(() => onInfo("about"))} /><Item icon="navigate-outline" title="How it works" copy="Post, match, hand off, track delivery, and complete safely." palette={palette} onPress={() => tap(() => onInfo("how_it_works"))} /><Item icon="shield-checkmark-outline" title="Safety" copy="Lawful items, honest declarations, verification, and reporting guidance." palette={palette} onPress={() => tap(() => onInfo("safety"))} /><Item icon="mail-outline" title="Contact" copy="BridgeX support and the secure contact route." palette={palette} onPress={() => tap(() => onInfo("contact"))} /><Item icon="download-outline" title="Downloads" copy="Android, desktop, and available platform release information." palette={palette} onPress={() => tap(() => onInfo("downloads"))} /></Section>
    <Section title="Legal" palette={palette}><Item icon="document-text-outline" title="Legal overview" copy="BridgeX’s platform role and members’ responsibilities." palette={palette} onPress={() => tap(() => onInfo("legal"))} /><Item icon="reader-outline" title="Terms" copy="Rules for lawful posts, transport, matching, and platform conduct." palette={palette} onPress={() => tap(() => onInfo("terms"))} /><Item icon="lock-closed-outline" title="Privacy" copy="How private account, location, and verification data are handled." palette={palette} onPress={() => tap(() => onInfo("privacy"))} /></Section>
  </ScrollView>;
}
function Section({ title, children, palette }: { title: string; children: ReactNode; palette: ReturnType<typeof useBridgeXAppearance> }) { return <View style={styles.section}><Text style={[styles.sectionTitle, { color: palette.text }]}>{title}</Text><View style={[styles.list, { backgroundColor: palette.surface, borderColor: palette.border }]}>{children}</View></View>; }
function Item({ icon, title, copy, onPress, palette, emphasis = false, badge = 0 }: { icon: React.ComponentProps<typeof Ionicons>["name"]; title: string; copy: string; onPress: () => void; palette: ReturnType<typeof useBridgeXAppearance>; emphasis?: boolean; badge?: number }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.item, { borderBottomColor: palette.border }, emphasis && { backgroundColor: palette.primarySoft }, pressed && styles.pressed]}><View style={[styles.icon, { backgroundColor: emphasis ? palette.primarySoft : palette.primarySoft }]}><Ionicons name={icon} size={18} color={emphasis ? palette.accent : palette.primary} /></View><View style={styles.itemCopy}><View style={styles.itemTitleRow}><Text style={[styles.itemTitle, { color: emphasis ? palette.accent : palette.text }]}>{title}</Text>{badge > 0 ? <Text style={styles.countBadge}>{badge > 99 ? "99+" : badge}</Text> : null}</View><Text style={[styles.itemDescription, { color: palette.muted }]}>{copy}</Text></View><Ionicons name="chevron-forward" size={19} color={emphasis ? palette.accent : palette.primary} /></Pressable>; }
const styles = StyleSheet.create({ page: { flex: 1 }, content: { gap: 20, padding: 20, paddingBottom: 106 }, eyebrow: { fontSize: 10, fontWeight: "900", letterSpacing: 1.5 }, title: { fontFamily: "serif", fontSize: 31, fontWeight: "800", letterSpacing: -1, marginTop: -14 }, copy: { fontSize: 13, lineHeight: 20, marginTop: -14 }, guest: { borderRadius: 16, borderWidth: 1, padding: 14 }, guestTitle: { fontSize: 14, fontWeight: "900" }, guestCopy: { fontSize: 12, lineHeight: 18, marginTop: 5 }, section: { gap: 9 }, sectionTitle: { fontSize: 16, fontWeight: "900" }, list: { borderRadius: 17, borderWidth: 1, overflow: "hidden" }, item: { alignItems: "center", borderBottomWidth: 1, flexDirection: "row", gap: 11, minHeight: 68, paddingHorizontal: 13, paddingVertical: 11 }, icon: { alignItems: "center", borderRadius: 13, height: 34, justifyContent: "center", width: 34 }, itemCopy: { flex: 1 }, itemTitleRow: { alignItems: "center", flexDirection: "row", gap: 6 }, itemTitle: { fontSize: 13, fontWeight: "900" }, countBadge: { backgroundColor: "#c94d3d", borderRadius: 10, color: "#fff", fontSize: 9, fontWeight: "900", overflow: "hidden", paddingHorizontal: 6, paddingVertical: 2 }, itemDescription: { fontSize: 11, lineHeight: 16, marginTop: 2 }, pressed: { opacity: 0.75, transform: [{ scale: 0.985 }] } });
