import * as Haptics from "expo-haptics";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import type { NativeInfoSection } from "../types";

type Props = { signedIn: boolean; onProfile: () => void; onUpdates: () => void; onPayments: () => void; onInfo: (section: NativeInfoSection) => void };

export function MoreScreen({ signedIn, onProfile, onUpdates, onPayments, onInfo }: Props) {
  const tap = (callback: () => void) => { void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); callback(); };
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>BRIDGEX</Text><Text style={styles.title}>More</Text><Text style={styles.copy}>Account settings, support, downloads, safety, and the BridgeX legal information in one place.</Text>{signedIn ? <Section title="Your account"><Item icon="◉" title="Profile & verification" copy="Private contact details, language, currency, and identity review." onPress={() => tap(onProfile)} /><Item icon="•" title="Updates" copy="Account, order, payment, and support notices." onPress={() => tap(onUpdates)} /><Item icon="¥" title="Payments" copy="Protected payment records and traveler payouts." onPress={() => tap(onPayments)} /></Section> : <View style={styles.guest}><Text style={styles.guestTitle}>Browsing as a guest</Text><Text style={styles.guestCopy}>Sign in to manage a profile, post, respond, use protected messaging, or open private payment records.</Text></View>}<Section title="Discover BridgeX"><Item icon="✦" title="About us" copy="The purpose and member-to-member model behind BridgeX." onPress={() => tap(() => onInfo("about"))} /><Item icon="↗" title="How it works" copy="Post, match, hand off, track delivery, and complete safely." onPress={() => tap(() => onInfo("how_it_works"))} /><Item icon="✓" title="Safety" copy="Lawful items, honest declarations, verification, and reporting guidance." onPress={() => tap(() => onInfo("safety"))} /><Item icon="✉" title="Contact" copy="BridgeX support and the secure contact route." onPress={() => tap(() => onInfo("contact"))} /><Item icon="↓" title="Downloads" copy="Android, desktop, and available platform release information." onPress={() => tap(() => onInfo("downloads"))} /></Section><Section title="Legal"><Item icon="◫" title="Legal overview" copy="BridgeX’s platform role and members’ responsibilities." onPress={() => tap(() => onInfo("legal"))} /><Item icon="§" title="Terms" copy="Rules for lawful posts, transport, matching, and platform conduct." onPress={() => tap(() => onInfo("terms"))} /><Item icon="◌" title="Privacy" copy="How private account, location, and verification data are handled." onPress={() => tap(() => onInfo("privacy"))} /></Section></ScrollView>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text><View style={styles.list}>{children}</View></View>; }
function Item({ icon, title, copy, onPress }: { icon: string; title: string; copy: string; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.item, pressed && styles.pressed]}><View style={styles.icon}><Text style={styles.iconText}>{icon}</Text></View><View style={styles.itemCopy}><Text style={styles.itemTitle}>{title}</Text><Text style={styles.itemDescription}>{copy}</Text></View><Text style={styles.arrow}>›</Text></Pressable>; }

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#f7f5ef" }, content: { gap: 20, padding: 20, paddingBottom: 106 }, eyebrow: { color: "#2d8d62", fontSize: 10, fontWeight: "900", letterSpacing: 1.5 }, title: { color: "#172126", fontFamily: "serif", fontSize: 31, fontWeight: "800", letterSpacing: -1, marginTop: -14 }, copy: { color: "#627073", fontSize: 13, lineHeight: 20, marginTop: -14 }, guest: { backgroundColor: "#fff7de", borderColor: "#ead19a", borderRadius: 16, borderWidth: 1, padding: 14 }, guestTitle: { color: "#765b1a", fontSize: 14, fontWeight: "900" }, guestCopy: { color: "#6f5f37", fontSize: 12, lineHeight: 18, marginTop: 5 }, section: { gap: 9 }, sectionTitle: { color: "#263438", fontSize: 16, fontWeight: "900" }, list: { backgroundColor: "#fff", borderColor: "#dfe5dd", borderRadius: 17, borderWidth: 1, overflow: "hidden" }, item: { alignItems: "center", borderBottomColor: "#edf0eb", borderBottomWidth: 1, flexDirection: "row", gap: 11, minHeight: 68, paddingHorizontal: 13, paddingVertical: 11 }, icon: { alignItems: "center", backgroundColor: "#e6f2e8", borderRadius: 13, height: 32, justifyContent: "center", width: 32 }, iconText: { color: "#176447", fontSize: 15, fontWeight: "900" }, itemCopy: { flex: 1 }, itemTitle: { color: "#263438", fontSize: 13, fontWeight: "900" }, itemDescription: { color: "#697679", fontSize: 11, lineHeight: 16, marginTop: 2 }, arrow: { color: "#176447", fontSize: 22, fontWeight: "500" }, pressed: { opacity: 0.75, transform: [{ scale: 0.985 }] } });
