import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from "react-native";
import { enqueueOfflineAction } from "../lib/cache";
import { loadNotifications, markNotificationRead } from "../lib/api";
import { supabase } from "../lib/supabase";
import type { NativeNotification } from "../types";

export function NotificationsScreen({ userId }: { userId: string }) {
  const [items, setItems] = useState<NativeNotification[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState("");
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); try { setError(""); setItems(await loadNotifications(userId)); } catch (failure: any) { setError(failure?.message || "BridgeX could not load updates."); } finally { setLoading(false); setRefreshing(false); } }, [userId]);
  useEffect(() => { void load(); const channel = supabase.channel(`native-notifications-${userId}`).on("postgres_changes", { event: "*", schema: "public", table: "notifications", filter: `user_id=eq.${userId}` }, () => void load(true)).subscribe(); return () => { void supabase.removeChannel(channel); }; }, [load, userId]);
  const read = async (item: NativeNotification) => { if (item.read_at) return; try { await markNotificationRead(userId, item.id); setItems(current => current.map(value => value.id === item.id ? { ...value, read_at: new Date().toISOString() } : value)); } catch { await enqueueOfflineAction({ id: `notification-read:${item.id}`, type: "notification-read", payload: { notificationId: item.id }, createdAt: Date.now() }); setItems(current => current.map(value => value.id === item.id ? { ...value, read_at: new Date().toISOString() } : value)); } };
  return <View style={styles.page}><View style={styles.head}><Text style={styles.eyebrow}>ACCOUNT ACTIVITY</Text><Text style={styles.title}>Updates</Text><Text style={styles.copy}>Newest 30 protected account updates.</Text></View>{loading ? <View style={styles.center}><ActivityIndicator color="#2d8d62" /></View> : <FlatList data={items} keyExtractor={item => item.id} contentContainerStyle={styles.list} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor="#2d8d62" />} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>No updates yet</Text><Text style={styles.emptyCopy}>Payment, safety, deal, and account updates will appear here.</Text></View>} renderItem={({ item }) => <Pressable onPress={() => void read(item)} style={[styles.item, !item.read_at && styles.unread]}><View style={[styles.dot, !item.read_at && styles.dotUnread]} /><View style={styles.itemCopy}><View style={styles.itemHead}><Text style={styles.itemTitle}>{item.title || "BridgeX update"}</Text><Text style={styles.time}>{new Date(item.created_at).toLocaleDateString()}</Text></View><Text style={styles.body}>{item.body || "Open this update for more details."}</Text></View></Pressable>} />}{error ? <Text style={styles.error}>{error}</Text> : null}</View>;
}

const styles = StyleSheet.create({ page: { backgroundColor: "#f7f5ef", flex: 1 }, head: { paddingHorizontal: 20, paddingTop: 5 }, eyebrow: { color: "#2d8d62", fontSize: 10, fontWeight: "900", letterSpacing: 1.5 }, title: { color: "#172126", fontFamily: "serif", fontSize: 30, fontWeight: "800", letterSpacing: -0.9, marginTop: 3 }, copy: { color: "#687679", fontSize: 13, marginTop: 3 }, center: { alignItems: "center", flex: 1, justifyContent: "center" }, list: { padding: 20, paddingTop: 18 }, item: { alignItems: "flex-start", backgroundColor: "#fff", borderBottomColor: "#e5e9e3", borderBottomWidth: 1, flexDirection: "row", gap: 10, padding: 15 }, unread: { backgroundColor: "#f5fbf6" }, dot: { backgroundColor: "#d4dcd5", borderRadius: 5, height: 9, marginTop: 5, width: 9 }, dotUnread: { backgroundColor: "#e1a136" }, itemCopy: { flex: 1 }, itemHead: { alignItems: "center", flexDirection: "row", gap: 8, justifyContent: "space-between" }, itemTitle: { color: "#29373a", flex: 1, fontSize: 14, fontWeight: "900" }, time: { color: "#7b8889", fontSize: 10 }, body: { color: "#667477", fontSize: 12, lineHeight: 18, marginTop: 4 }, empty: { alignItems: "center", backgroundColor: "#fff", borderColor: "#dbe2da", borderRadius: 16, borderStyle: "dashed", borderWidth: 1, padding: 26 }, emptyTitle: { color: "#263438", fontSize: 16, fontWeight: "900" }, emptyCopy: { color: "#697779", fontSize: 12, lineHeight: 18, marginTop: 6, textAlign: "center" }, error: { color: "#924638", fontSize: 12, padding: 15, textAlign: "center" } });
