import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { supabase } from "../lib/supabase";
import type { MarketplacePost } from "../types";

type Props = { post: MarketplacePost; signedIn: boolean; onBack: () => void; onRespond: () => void; };

export function PostDetailScreen({ post, signedIn, onBack, onRespond }: Props) {
  const media = post.mediaPaths[0] ? supabase.storage.from("request-media").getPublicUrl(post.mediaPaths[0]).data.publicUrl : undefined;
  const isRequest = post.kind === "requests";
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><Pressable onPress={onBack} style={styles.back}><Text style={styles.backText}>‹ Back to marketplace</Text></Pressable>{media ? <Image source={{ uri: media }} style={styles.image} /> : <View style={styles.mediaFallback}><Text style={styles.fallbackIcon}>⌑</Text></View>}<View style={styles.tagRow}><Text style={styles.tag}>{isRequest ? "ITEM REQUEST" : "CARRY SPACE"}</Text><Text style={styles.live}>LIVE</Text></View><Text style={styles.title}>{post.title}</Text>{post.category ? <Text style={styles.category}>{post.category}</Text> : null}<View style={styles.infoCard}><Info label="Route" value={post.route} /><Info label={isRequest ? "Requested weight" : "Remaining capacity"} value={post.weight} /><Info label={isRequest ? "Maximum budget" : "Price"} value={`${post.currency} ${post.price.toLocaleString()}`} /><Info label="Published" value={new Date(post.createdAt).toLocaleDateString()} /></View><View style={styles.safety}><Text style={styles.safetyTitle}>Protected response</Text><Text style={styles.safetyCopy}>Respond only if you can meet the stated route, timing, lawful-item, and handling requirements. Exact private contact details are shared only after a protected match.</Text></View><Pressable onPress={onRespond} style={styles.primary}><Text style={styles.primaryText}>{signedIn ? isRequest ? "Make an offer" : "Show interest" : "Sign in to respond"}</Text></Pressable></ScrollView>;
}

function Info({ label, value }: { label: string; value: string }) { return <View style={styles.info}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View>; }

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#f7f5ef" }, content: { padding: 20, paddingBottom: 42 }, back: { alignSelf: "flex-start", paddingBottom: 16, paddingTop: 2 }, backText: { color: "#176447", fontSize: 14, fontWeight: "900" }, image: { backgroundColor: "#e7f1e8", borderRadius: 18, height: 235, width: "100%" }, mediaFallback: { alignItems: "center", backgroundColor: "#e7f1e8", borderRadius: 18, height: 190, justifyContent: "center" }, fallbackIcon: { color: "#2d8d62", fontSize: 44 }, tagRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginTop: 18 }, tag: { backgroundColor: "#e7f4ea", borderRadius: 20, color: "#23784f", fontSize: 10, fontWeight: "900", letterSpacing: 0.8, overflow: "hidden", paddingHorizontal: 9, paddingVertical: 6 }, live: { color: "#6f7d80", fontSize: 11, fontWeight: "900" }, title: { color: "#172126", fontSize: 29, fontWeight: "900", letterSpacing: -0.9, lineHeight: 34, marginTop: 13 }, category: { color: "#86600d", fontSize: 13, fontWeight: "800", marginTop: 6 }, infoCard: { backgroundColor: "#fff", borderColor: "#dee4dc", borderRadius: 18, borderWidth: 1, marginTop: 19, padding: 16 }, info: { borderBottomColor: "#edf0eb", borderBottomWidth: 1, gap: 4, paddingVertical: 11 }, infoLabel: { color: "#7a8788", fontSize: 11, fontWeight: "800", textTransform: "uppercase" }, infoValue: { color: "#263438", fontSize: 14, fontWeight: "800", lineHeight: 20 }, safety: { backgroundColor: "#eef6ef", borderRadius: 16, marginTop: 16, padding: 15 }, safetyTitle: { color: "#176447", fontSize: 14, fontWeight: "900" }, safetyCopy: { color: "#456552", fontSize: 13, lineHeight: 20, marginTop: 5 }, primary: { alignItems: "center", backgroundColor: "#172126", borderRadius: 14, marginTop: 20, paddingVertical: 16 }, primaryText: { color: "#fff", fontSize: 15, fontWeight: "900" } });
