import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { Swipeable } from "react-native-gesture-handler";
import { archiveNativeRequest, loadNativeWorkspace, type NativeWorkspace } from "../lib/api";

export type WorkspaceSection = "active_orders" | "requests" | "carry" | "completed";
type Props = { userId: string; section: WorkspaceSection; onBack: () => void; onOpenMessages: () => void };
const complete = (order: NativeWorkspace["orders"][number]) => order.escrow_status === "released" || ["released", "completed", "cancelled"].includes(order.fulfillment_status);
const titleFor: Record<WorkspaceSection, string> = { active_orders: "Active orders", requests: "My item requests", carry: "My carry space", completed: "Completed orders" };

export function WorkspaceRecordsScreen({ userId, section, onBack, onOpenMessages }: Props) {
  const [workspace, setWorkspace] = useState<NativeWorkspace>({ requests: [], listings: [], orders: [] });
  const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { setWorkspace(await loadNativeWorkspace(userId)); } catch (error: any) { Alert.alert("BridgeX", error?.message || "Could not load this workspace list."); } finally { setLoading(false); } }, [userId]);
  useEffect(() => { void load(); }, [load]);
  const archive = (request: NativeWorkspace["requests"][number]) => Alert.alert("Remove from My item requests?", "This hides the request from your personal list and closes its public post. Protected order history is not deleted.", [{ text: "Keep", style: "cancel" }, { text: "Remove", style: "destructive", onPress: () => void (async () => { try { await archiveNativeRequest(request.id); await load(); } catch (error: any) { Alert.alert("Could not remove request", error?.message || "This request may still be part of an active protected order."); } })() }]);
  const data = section === "requests" ? workspace.requests : section === "carry" ? workspace.listings : workspace.orders.filter(order => section === "completed" ? complete(order) : !complete(order));
  return <View style={styles.page}><View style={styles.head}><Pressable onPress={onBack}><Text style={styles.back}>‹ Workspace</Text></Pressable><Text style={styles.eyebrow}>MEMBER RECORDS</Text><Text style={styles.title}>{titleFor[section]}</Text><Text style={styles.copy}>{section === "requests" ? "Swipe an eligible request left to remove it after any protected order is finished." : "Open only the records relevant to this section, without crowding your workspace overview."}</Text></View>{loading ? <View style={styles.center}><ActivityIndicator color="#2d8d62" /></View> : <FlatList data={data as any[]} keyExtractor={item => item.id} contentContainerStyle={styles.list} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>Nothing here yet</Text><Text style={styles.emptyCopy}>Records appear here as your BridgeX activity changes.</Text></View>} renderItem={({ item }) => section === "requests" ? <Swipeable renderRightActions={() => <Pressable onPress={() => archive(item)} style={styles.remove}><Text style={styles.removeText}>Remove</Text></Pressable>} overshootRight={false}><RequestRow request={item} /></Swipeable> : section === "carry" ? <ListingRow listing={item} /> : <OrderRow order={item} onOpenMessages={onOpenMessages} />} />}</View>;
}
function RequestRow({ request }: { request: NativeWorkspace["requests"][number] }) { return <View style={styles.row}><Text style={styles.rowTitle}>{request.title}</Text><Text style={styles.rowCopy}>{request.purchase_country || "Origin"} → {request.destination_city || request.destination_country || "Destination"}</Text><Text style={styles.status}>{request.status.replace(/_/g, " ")}</Text></View>; }
function ListingRow({ listing }: { listing: NativeWorkspace["listings"][number] }) { return <View style={styles.row}><Text style={styles.rowTitle}>{listing.origin_city || "Origin"} → {listing.destination_city || listing.destination_country || "Destination"}</Text><Text style={styles.rowCopy}>{listing.available_weight_kg ?? 0} kg · {new Date(listing.departure_at).toLocaleDateString()}</Text><Text style={styles.status}>{listing.status.replace(/_/g, " ")}</Text></View>; }
function OrderRow({ order, onOpenMessages }: { order: NativeWorkspace["orders"][number]; onOpenMessages: () => void }) { return <Pressable onPress={onOpenMessages} style={styles.row}><Text style={styles.rowTitle}>{order.reference}</Text><Text style={styles.rowCopy}>{order.counterpart_name || "BridgeX member"} · {order.currency || "BDT"} {Number(order.amount_bdt || 0).toLocaleString()}</Text><Text style={styles.status}>{order.fulfillment_status.replace(/_/g, " ")}</Text></Pressable>; }
const styles = StyleSheet.create({ page: { backgroundColor: "#f7f5ef", flex: 1 }, head: { padding: 20, paddingBottom: 8 }, back: { color: "#176447", fontSize: 14, fontWeight: "900" }, eyebrow: { color: "#2d8d62", fontSize: 10, fontWeight: "900", letterSpacing: 1.4, marginTop: 15 }, title: { color: "#172126", fontFamily: "serif", fontSize: 30, fontWeight: "800", marginTop: 3 }, copy: { color: "#687679", fontSize: 13, lineHeight: 19, marginTop: 4 }, center: { alignItems: "center", flex: 1, justifyContent: "center" }, list: { gap: 10, padding: 20 }, row: { backgroundColor: "#fff", borderColor: "#dce4db", borderRadius: 15, borderWidth: 1, padding: 15 }, rowTitle: { color: "#29373a", fontSize: 15, fontWeight: "900" }, rowCopy: { color: "#687679", fontSize: 12, lineHeight: 18, marginTop: 5 }, status: { alignSelf: "flex-start", backgroundColor: "#e7f4ea", borderRadius: 20, color: "#176447", fontSize: 10, fontWeight: "900", marginTop: 9, overflow: "hidden", paddingHorizontal: 8, paddingVertical: 5, textTransform: "uppercase" }, remove: { alignItems: "center", backgroundColor: "#a54132", borderRadius: 15, justifyContent: "center", marginBottom: 1, marginLeft: 8, width: 94 }, removeText: { color: "#fff", fontSize: 12, fontWeight: "900" }, empty: { alignItems: "center", backgroundColor: "#fff", borderColor: "#dbe2da", borderRadius: 16, borderStyle: "dashed", borderWidth: 1, padding: 26 }, emptyTitle: { color: "#263438", fontSize: 16, fontWeight: "900" }, emptyCopy: { color: "#687679", fontSize: 12, lineHeight: 18, marginTop: 6, textAlign: "center" } });
