import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { declineNativeOwnerResponse, loadNativeOwnerResponses, startNativeOwnerPayment, type NativeOwnerResponse } from "../lib/api";

export function WorkspaceResponsesScreen({ userId, onBack, onPaymentStarted, initialPostId }: { userId: string; onBack: () => void; onPaymentStarted: (paymentId: string) => void; initialPostId?: string }) {
  const [responses, setResponses] = useState<NativeOwnerResponse[]>([]);
  const [loading, setLoading] = useState(true);
  const [busyId, setBusyId] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { setResponses(await loadNativeOwnerResponses(userId)); } catch (error: any) { Alert.alert("BridgeX", error?.message || "Could not load offers and interests."); } finally { setLoading(false); } }, [userId]);
  useEffect(() => { void load(); }, [load]);
  const beginPayment = (response: NativeOwnerResponse) => Alert.alert(response.kind === "offer" ? "Accept and pay?" : "Accept and request payment?", "Continue only if you can meet the lawful item, route, timing, and handling requirements. The protected payment record opens next.", [{ text: "Not yet", style: "cancel" }, { text: "Continue", onPress: () => void (async () => { setBusyId(response.id); try { const paymentId = await startNativeOwnerPayment(response.kind, response.id); onPaymentStarted(paymentId); } catch (error: any) { Alert.alert("Could not start payment", error?.message || "This response may no longer be available."); } finally { setBusyId(null); } })() }]);
  const decline = (response: NativeOwnerResponse) => Alert.alert("Decline this response?", "The member can continue browsing other open posts.", [{ text: "Keep", style: "cancel" }, { text: "Decline", style: "destructive", onPress: () => void (async () => { setBusyId(response.id); try { await declineNativeOwnerResponse(response.kind, response.id); await load(); } catch (error: any) { Alert.alert("Could not decline", error?.message || "Please try again."); } finally { setBusyId(null); } })() }]);
  const visibleResponses = initialPostId ? responses.filter(response => response.postId === initialPostId) : responses;
  const grouped = visibleResponses.reduce<Record<string, NativeOwnerResponse[]>>((groups, response) => { (groups[`${response.kind}:${response.postId}`] ||= []).push(response); return groups; }, {});
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><Pressable onPress={onBack}><Text style={styles.back}>‹ Workspace</Text></Pressable><Text style={styles.eyebrow}>INCOMING RESPONSES</Text><Text style={styles.title}>{initialPostId ? "Post responses" : "Offers and interests"}</Text><Text style={styles.copy}>Each response stays under its own post. Start payment only for the one offer you choose, or for available carry-space capacity.</Text>{loading ? <View style={styles.loading}><ActivityIndicator color="#2d8d62" /></View> : Object.values(grouped).length ? Object.values(grouped).map(group => <View key={`${group[0].kind}:${group[0].postId}`} style={styles.group}><View style={styles.groupHead}><Text style={styles.groupLabel}>{group[0].kind === "offer" ? "MY ITEM REQUEST" : "MY CARRY SPACE"}</Text><Text style={styles.groupCount}>{group.length} response{group.length === 1 ? "" : "s"}</Text></View><Text style={styles.groupTitle}>{group[0].postTitle}</Text>{group.map(response => <View key={response.id} style={styles.card}><View style={styles.cardHead}><View><Text style={styles.person}>{response.participantName} {response.participantVerified ? "· Verified" : "· Not verified"}</Text><Text style={styles.time}>{new Date(response.createdAt).toLocaleString()}</Text></View><Text style={styles.status}>{response.status.replace(/_/g, " ")}</Text></View><Text style={styles.amount}>{response.currency} {response.amount.toLocaleString()}</Text><Text style={styles.details}>{response.details}</Text>{response.note ? <Text style={styles.note}>{response.note}</Text> : null}{response.status === "pending" ? <View style={styles.actions}><Pressable disabled={busyId === response.id} onPress={() => beginPayment(response)} style={[styles.accept, busyId === response.id && styles.disabled]}><Text style={styles.acceptText}>{busyId === response.id ? "Opening…" : response.kind === "offer" ? "Accept & pay" : "Accept · request payment"}</Text></Pressable><Pressable disabled={busyId === response.id} onPress={() => decline(response)} style={styles.decline}><Text style={styles.declineText}>Decline</Text></Pressable></View> : response.status === "pending_payment" ? <Text style={styles.pending}>Payment step has started. Open Payments to continue.</Text> : response.status === "payment_verifying" ? <Text style={styles.verifying}>Payment evidence is under review.</Text> : null}</View>)}</View>) : <View style={styles.empty}><Text style={styles.emptyTitle}>No offers or interests yet</Text><Text style={styles.emptyCopy}>Incoming responses will appear here under the correct request or carry-space post.</Text></View>}</ScrollView>;
}

const styles = StyleSheet.create({ page: { backgroundColor: "#f7f5ef", flex: 1 }, content: { gap: 14, padding: 20, paddingBottom: 42 }, back: { color: "#176447", fontSize: 14, fontWeight: "900" }, eyebrow: { color: "#2d8d62", fontSize: 10, fontWeight: "900", letterSpacing: 1.4, marginTop: 5 }, title: { color: "#172126", fontFamily: "serif", fontSize: 30, fontWeight: "800", marginTop: 2 }, copy: { color: "#687679", fontSize: 13, lineHeight: 19 }, loading: { alignItems: "center", paddingVertical: 30 }, group: { backgroundColor: "#eceee8", borderRadius: 17, gap: 10, padding: 13 }, groupHead: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, groupLabel: { color: "#176447", fontSize: 10, fontWeight: "900", letterSpacing: 0.6 }, groupCount: { backgroundColor: "#fff", borderRadius: 12, color: "#176447", fontSize: 10, fontWeight: "900", overflow: "hidden", paddingHorizontal: 8, paddingVertical: 4 }, groupTitle: { color: "#263438", fontSize: 15, fontWeight: "900" }, card: { backgroundColor: "#fff", borderColor: "#d9e1d9", borderRadius: 14, borderWidth: 1, gap: 8, padding: 13 }, cardHead: { alignItems: "flex-start", flexDirection: "row", justifyContent: "space-between" }, person: { color: "#263438", fontSize: 13, fontWeight: "900" }, time: { color: "#748083", fontSize: 10, marginTop: 3 }, status: { backgroundColor: "#e7f4ea", borderRadius: 12, color: "#176447", fontSize: 9, fontWeight: "900", maxWidth: 105, overflow: "hidden", paddingHorizontal: 7, paddingVertical: 4, textTransform: "uppercase" }, amount: { color: "#172126", fontSize: 17, fontWeight: "900" }, details: { color: "#506064", fontSize: 12, lineHeight: 18 }, note: { color: "#596669", fontSize: 12, fontStyle: "italic", lineHeight: 18 }, actions: { flexDirection: "row", gap: 8, marginTop: 2 }, accept: { backgroundColor: "#176447", borderRadius: 9, flex: 1, paddingHorizontal: 9, paddingVertical: 10 }, acceptText: { color: "#fff", fontSize: 11, fontWeight: "900", textAlign: "center" }, decline: { backgroundColor: "#fff4ef", borderRadius: 9, paddingHorizontal: 11, paddingVertical: 10 }, declineText: { color: "#a24135", fontSize: 11, fontWeight: "900" }, pending: { backgroundColor: "#edf6fd", borderRadius: 9, color: "#27648b", fontSize: 11, fontWeight: "800", padding: 9 }, verifying: { backgroundColor: "#fff7e5", borderRadius: 9, color: "#7d5b13", fontSize: 11, fontWeight: "800", padding: 9 }, empty: { alignItems: "center", backgroundColor: "#fff", borderColor: "#dbe2da", borderRadius: 16, borderStyle: "dashed", borderWidth: 1, padding: 28 }, emptyTitle: { color: "#263438", fontSize: 16, fontWeight: "900" }, emptyCopy: { color: "#687679", fontSize: 12, lineHeight: 18, marginTop: 6, textAlign: "center" }, disabled: { opacity: 0.55 } });
