// Generated from reviewed BridgeX localization output. Do not hand-edit language values here.

export const LANGUAGE_OPTIONS = [
  { code: "en", label: "English", nativeLabel: "English" },
  { code: "zh-CN", label: "Chinese (Simplified)", nativeLabel: "简体中文" },
  { code: "fr", label: "French", nativeLabel: "Français" },
  { code: "es", label: "Spanish", nativeLabel: "Español" },
  { code: "de", label: "German", nativeLabel: "Deutsch" },
  { code: "ar", label: "Arabic", nativeLabel: "العربية" },
  { code: "ja", label: "Japanese", nativeLabel: "日本語" },
  { code: "ko", label: "Korean", nativeLabel: "한국어" },
  { code: "bn", label: "Bangla", nativeLabel: "বাংলা" },
  { code: "hi", label: "Hindi", nativeLabel: "हिन्दी" },
  { code: "ur", label: "Urdu", nativeLabel: "اردو" },
] as const;

export type SystemLanguage = (typeof LANGUAGE_OPTIONS)[number]["code"];
export const RTL_LANGUAGES: readonly SystemLanguage[] = ["ar", "ur"];

export const TRANSLATIONS = {
  "en": {
    "language": "Language",
    "chooseLanguage": "Choose language",
    "systemLanguage": "System language",
    "systemLanguageDescription": "Choose the language BridgeX uses for menus, account access, and settings.",
    "accountAccess": "Account access",
    "protectedOrderTrust": "Protected orders start with a trusted account.",
    "signIn": "Sign in",
    "createAccount": "Create account",
    "displayName": "Display name",
    "emailAddress": "Email address",
    "password": "Password",
    "continueWithGoogle": "Continue with Google",
    "orUseEmail": "or use email",
    "signInSecurely": "Sign in securely",
    "createSecureAccount": "Create secure account",
    "browseAsGuest": "Browse as guest",
    "emailConfirmation": "Confirm your email before your first sign-in.",
    "marketplace": "Marketplace",
    "howItWorks": "How it works",
    "safety": "Safety",
    "contact": "Contact",
    "listSpace": "List space",
    "postItem": "Post item",
    "settings": "Settings",
    "saveProfile": "Save profile",
    "downloads": "Downloads",
    "downloadAndroid": "Download for Android",
    "downloadWindows": "Download for Windows",
    "harmonyOS": "HarmonyOS version",
    "macOS": "macOS version",
    "comingSoon": "Coming soon",
    "legal": "Legal",
    "terms": "Terms",
    "privacy": "Privacy",
    "myAccount": "My account"
  },
  "zh-CN": {
    "language": "语言",
    "chooseLanguage": "选择语言",
    "systemLanguage": "系统语言",
    "systemLanguageDescription": "选择 BridgeX 在菜单、帐户访问和设置中使用的语言。",
    "accountAccess": "帐户访问",
    "protectedOrderTrust": "受保护的订单始于受信任的帐户。",
    "signIn": "登录",
    "createAccount": "创建帐户",
    "displayName": "显示名称",
    "emailAddress": "电子邮箱地址",
    "password": "密码",
    "continueWithGoogle": "使用 Google 登录",
    "orUseEmail": "或使用电子邮件",
    "signInSecurely": "安全登录",
    "createSecureAccount": "创建安全帐户",
    "browseAsGuest": "以访客身份浏览",
    "emailConfirmation": "首次登录前请确认您的电子邮件。",
    "marketplace": "市场",
    "howItWorks": "如何运作",
    "safety": "安全",
    "contact": "联系",
    "listSpace": "列出空间",
    "postItem": "发布物品",
    "settings": "设置",
    "saveProfile": "保存资料",
    "downloads": "下载",
    "downloadAndroid": "下载 Android 版",
    "downloadWindows": "下载 Windows 版",
    "harmonyOS": "HarmonyOS 版本",
    "macOS": "macOS 版本",
    "comingSoon": "即将推出",
    "legal": "法律",
    "terms": "条款",
    "privacy": "隐私",
    "myAccount": "我的帐户"
  },
  "fr": {
    "language": "Langue",
    "chooseLanguage": "Choisir la langue",
    "systemLanguage": "Langue du système",
    "systemLanguageDescription": "Choisissez la langue que BridgeX utilise pour les menus, l'accès au compte et les paramètres.",
    "accountAccess": "Accès au compte",
    "protectedOrderTrust": "Les commandes protégées commencent par un compte de confiance.",
    "signIn": "Se connecter",
    "createAccount": "Créer un compte",
    "displayName": "Nom affiché",
    "emailAddress": "Adresse e-mail",
    "password": "Mot de passe",
    "continueWithGoogle": "Continuer avec Google",
    "orUseEmail": "ou utiliser l'e‑mail",
    "signInSecurely": "Connexion sécurisée",
    "createSecureAccount": "Créer un compte sécurisé",
    "browseAsGuest": "Parcourir en tant qu'invité",
    "emailConfirmation": "Confirmez votre e‑mail avant votre première connexion.",
    "marketplace": "Place de marché",
    "howItWorks": "Comment ça marche",
    "safety": "Sécurité",
    "contact": "Contact",
    "listSpace": "Lister un espace",
    "postItem": "Publier un article",
    "settings": "Paramètres",
    "saveProfile": "Enregistrer le profil",
    "downloads": "Téléchargements",
    "downloadAndroid": "Télécharger pour Android",
    "downloadWindows": "Télécharger pour Windows",
    "harmonyOS": "Version HarmonyOS",
    "macOS": "Version macOS",
    "comingSoon": "Bientôt disponible",
    "legal": "Mentions légales",
    "terms": "Conditions",
    "privacy": "Confidentialité",
    "myAccount": "Mon compte"
  },
  "es": {
    "language": "Idioma",
    "chooseLanguage": "Elegir idioma",
    "systemLanguage": "Idioma del sistema",
    "systemLanguageDescription": "Elige el idioma que BridgeX usa en los menús, el acceso a la cuenta y la configuración.",
    "accountAccess": "Acceso a la cuenta",
    "protectedOrderTrust": "Los pedidos protegidos comienzan con una cuenta de confianza.",
    "signIn": "Iniciar sesión",
    "createAccount": "Crear cuenta",
    "displayName": "Nombre para mostrar",
    "emailAddress": "Correo electrónico",
    "password": "Contraseña",
    "continueWithGoogle": "Continuar con Google",
    "orUseEmail": "o usar correo",
    "signInSecurely": "Inicia sesión de forma segura",
    "createSecureAccount": "Crear cuenta segura",
    "browseAsGuest": "Navegar como invitado",
    "emailConfirmation": "Confirma tu correo electrónico antes de tu primer inicio de sesión.",
    "marketplace": "Mercado",
    "howItWorks": "Cómo funciona",
    "safety": "Seguridad",
    "contact": "Contacto",
    "listSpace": "Publicar espacio",
    "postItem": "Publicar artículo",
    "settings": "Ajustes",
    "saveProfile": "Guardar perfil",
    "downloads": "Descargas",
    "downloadAndroid": "Descargar para Android",
    "downloadWindows": "Descargar para Windows",
    "harmonyOS": "Versión HarmonyOS",
    "macOS": "Versión macOS",
    "comingSoon": "Próximamente",
    "legal": "Legal",
    "terms": "Términos",
    "privacy": "Privacidad",
    "myAccount": "Mi cuenta"
  },
  "de": {
    "language": "Sprache",
    "chooseLanguage": "Sprache wählen",
    "systemLanguage": "Systemsprache",
    "systemLanguageDescription": "Wählen Sie die Sprache, die BridgeX für Menüs, Kontozugriff und Einstellungen verwendet.",
    "accountAccess": "Kontozugriff",
    "protectedOrderTrust": "Geschützte Bestellungen beginnen mit einem vertrauenswürdigen Konto.",
    "signIn": "Anmelden",
    "createAccount": "Konto erstellen",
    "displayName": "Anzeigename",
    "emailAddress": "E-Mail-Adresse",
    "password": "Passwort",
    "continueWithGoogle": "Mit Google fortfahren",
    "orUseEmail": "oder E-Mail verwenden",
    "signInSecurely": "Sicher anmelden",
    "createSecureAccount": "Sicheres Konto erstellen",
    "browseAsGuest": "Als Gast durchsuchen",
    "emailConfirmation": "Bestätigen Sie Ihre E‑Mail vor der ersten Anmeldung.",
    "marketplace": "Marktplatz",
    "howItWorks": "Wie es funktioniert",
    "safety": "Sicherheit",
    "contact": "Kontakt",
    "listSpace": "Platz anbieten",
    "postItem": "Artikel einstellen",
    "settings": "Einstellungen",
    "saveProfile": "Profil speichern",
    "downloads": "Downloads",
    "downloadAndroid": "Für Android herunterladen",
    "downloadWindows": "Für Windows herunterladen",
    "harmonyOS": "HarmonyOS-Version",
    "macOS": "macOS-Version",
    "comingSoon": "Demnächst verfügbar",
    "legal": "Rechtliches",
    "terms": "Nutzungsbedingungen",
    "privacy": "Datenschutz",
    "myAccount": "Mein Konto"
  },
  "ar": {
    "language": "اللغة",
    "chooseLanguage": "اختر اللغة",
    "systemLanguage": "لغة النظام",
    "systemLanguageDescription": "اختر اللغة التي يستخدمها BridgeX في القوائم والوصول إلى الحساب والإعدادات.",
    "accountAccess": "الوصول إلى الحساب",
    "protectedOrderTrust": "تبدأ الطلبات المحمية بحساب موثوق.",
    "signIn": "تسجيل الدخول",
    "createAccount": "إنشاء حساب",
    "displayName": "اسم العرض",
    "emailAddress": "البريد الإلكتروني",
    "password": "كلمة المرور",
    "continueWithGoogle": "المتابعة عبر Google",
    "orUseEmail": "أو استخدم البريد الإلكتروني",
    "signInSecurely": "تسجيل دخول آمن",
    "createSecureAccount": "إنشاء حساب آمن",
    "browseAsGuest": "التصفح كزائر",
    "emailConfirmation": "قم بتأكيد بريدك الإلكتروني قبل أول تسجيل دخول.",
    "marketplace": "السوق",
    "howItWorks": "كيفية العمل",
    "safety": "السلامة",
    "contact": "اتصال",
    "listSpace": "قائمة المساحة",
    "postItem": "نشر عنصر",
    "settings": "الإعدادات",
    "saveProfile": "حفظ الملف الشخصي",
    "downloads": "التنزيلات",
    "downloadAndroid": "التنزيل لأندرويد",
    "downloadWindows": "التنزيل لويندوز",
    "harmonyOS": "إصدار HarmonyOS",
    "macOS": "إصدار macOS",
    "comingSoon": "قريبًا",
    "legal": "قانوني",
    "terms": "الشروط",
    "privacy": "الخصوصية",
    "myAccount": "حسابي"
  },
  "ja": {
    "language": "言語",
    "chooseLanguage": "言語を選択",
    "systemLanguage": "システム言語",
    "systemLanguageDescription": "BridgeX がメニュー、アカウントアクセス、設定で使用する言語を選んでください。",
    "accountAccess": "アカウントアクセス",
    "protectedOrderTrust": "保護された注文は信頼できるアカウントから始まります。",
    "signIn": "サインイン",
    "createAccount": "アカウントを作成",
    "displayName": "表示名",
    "emailAddress": "メールアドレス",
    "password": "パスワード",
    "continueWithGoogle": "Google で続行",
    "orUseEmail": "またはメールを使用",
    "signInSecurely": "安全にサインイン",
    "createSecureAccount": "安全なアカウントを作成",
    "browseAsGuest": "ゲストとして閲覧",
    "emailConfirmation": "初回サインイン前にメールを確認してください。",
    "marketplace": "マーケットプレイス",
    "howItWorks": "使い方",
    "safety": "安全性",
    "contact": "お問い合わせ",
    "listSpace": "スペースを掲載",
    "postItem": "アイテムを投稿",
    "settings": "設定",
    "saveProfile": "プロフィールを保存",
    "downloads": "ダウンロード",
    "downloadAndroid": "Android 版をダウンロード",
    "downloadWindows": "Windows 版をダウンロード",
    "harmonyOS": "HarmonyOS バージョン",
    "macOS": "macOS バージョン",
    "comingSoon": "近日公開",
    "legal": "法的情報",
    "terms": "利用規約",
    "privacy": "プライバシー",
    "myAccount": "マイアカウント"
  },
  "ko": {
    "language": "언어",
    "chooseLanguage": "언어 선택",
    "systemLanguage": "시스템 언어",
    "systemLanguageDescription": "메뉴, 계정 액세스 및 설정에 BridgeX가 사용할 언어를 선택하세요.",
    "accountAccess": "계정 액세스",
    "protectedOrderTrust": "보호된 주문은 신뢰할 수 있는 계정에서 시작됩니다.",
    "signIn": "로그인",
    "createAccount": "계정 만들기",
    "displayName": "표시 이름",
    "emailAddress": "이메일 주소",
    "password": "비밀번호",
    "continueWithGoogle": "Google로 계속",
    "orUseEmail": "또는 이메일 사용",
    "signInSecurely": "안전하게 로그인",
    "createSecureAccount": "안전한 계정 만들기",
    "browseAsGuest": "게스트로 둘러보기",
    "emailConfirmation": "첫 로그인 전에 이메일을 확인하세요。",
    "marketplace": "마켓플레이스",
    "howItWorks": "이용 방법",
    "safety": "안전",
    "contact": "문의",
    "listSpace": "공간 등록",
    "postItem": "상품 등록",
    "settings": "설정",
    "saveProfile": "프로필 저장",
    "downloads": "다운로드",
    "downloadAndroid": "Android용 다운로드",
    "downloadWindows": "Windows용 다운로드",
    "harmonyOS": "HarmonyOS 버전",
    "macOS": "macOS 버전",
    "comingSoon": "곧 제공",
    "legal": "법적 고지",
    "terms": "약관",
    "privacy": "개인정보",
    "myAccount": "내 계정"
  },
  "bn": {
    "language": "ভাষা",
    "chooseLanguage": "ভাষা নির্বাচন করুন",
    "systemLanguage": "সিস্টেম ভাষা",
    "systemLanguageDescription": "মেনু, অ্যাকাউন্ট অ্যাক্সেস এবং সেটিংসে BridgeX যে ভাষা ব্যবহার করবে তা বেছে নিন।",
    "accountAccess": "অ্যাকাউন্ট অ্যাক্সেস",
    "protectedOrderTrust": "সুরক্ষিত অর্ডারগুলি একটি বিশ্বাসযোগ্য অ্যাকাউন্ট থেকে শুরু হয়।",
    "signIn": "সাইন ইন",
    "createAccount": "অ্যাকাউন্ট তৈরি করুন",
    "displayName": "প্রদর্শন নাম",
    "emailAddress": "ইমেইল ঠিকানা",
    "password": "পাসওয়ার্ড",
    "continueWithGoogle": "Google দিয়ে চালিয়ে যান",
    "orUseEmail": "অথবা ইমেইল ব্যবহার করুন",
    "signInSecurely": "নিরাপদে সাইন ইন করুন",
    "createSecureAccount": "নিরাপদ অ্যাকাউন্ট তৈরি করুন",
    "browseAsGuest": "অতিথি হিসেবে ব্রাউজ করুন",
    "emailConfirmation": "প্রথম সাইন ইন এর আগে আপনার ইমেইল নিশ্চিত করুন।",
    "marketplace": "মার্কেটপ্লেস",
    "howItWorks": "এটি কীভাবে কাজ করে",
    "safety": "নিরাপত্তা",
    "contact": "যোগাযোগ",
    "listSpace": "স্পেস তালিকাভুক্ত করুন",
    "postItem": "আইটেম পোস্ট করুন",
    "settings": "সেটিংস",
    "saveProfile": "প্রোফাইল সংরক্ষণ করুন",
    "downloads": "ডাউনলোড",
    "downloadAndroid": "Android-এর জন্য ডাউনলোড",
    "downloadWindows": "Windows-এর জন্য ডাউনলোড",
    "harmonyOS": "HarmonyOS সংস্করণ",
    "macOS": "macOS সংস্করণ",
    "comingSoon": "শীঘ্রই আসছে",
    "legal": "আইনগত",
    "terms": "শর্তাবলী",
    "privacy": "গোপনীয়তা",
    "myAccount": "আমার অ্যাকাউন্ট"
  },
  "hi": {
    "language": "भाषा",
    "chooseLanguage": "भाषा चुनें",
    "systemLanguage": "सिस्टम भाषा",
    "systemLanguageDescription": "मेन्यू, अकाउंट एक्सेस और सेटिंग्स के लिए BridgeX किस भाषा का उपयोग करेगा चुनें।",
    "accountAccess": "खाता पहुँच",
    "protectedOrderTrust": "सुरक्षित ऑर्डर भरोसेमंद खाते से शुरू होते हैं।",
    "signIn": "साइन इन",
    "createAccount": "खाता बनाएं",
    "displayName": "प्रदर्शन नाम",
    "emailAddress": "ईमेल पता",
    "password": "पासवर्ड",
    "continueWithGoogle": "Google के साथ जारी रखें",
    "orUseEmail": "या ईमेल का उपयोग करें",
    "signInSecurely": "सुरक्षित रूप से साइन इन करें",
    "createSecureAccount": "सुरक्षित खाता बनाएं",
    "browseAsGuest": "अतिथि के रूप में ब्राउज़ करें",
    "emailConfirmation": "पहली साइन-इन से पहले अपना ईमेल सत्यापित करें।",
    "marketplace": "मार्केटप्लेस",
    "howItWorks": "यह कैसे काम करता है",
    "safety": "सुरक्षा",
    "contact": "संपर्क",
    "listSpace": "स्पेस सूचीबद्ध करें",
    "postItem": "आइटम पोस्ट करें",
    "settings": "सेटिंग्स",
    "saveProfile": "प्रोफ़ाइल सहेजें",
    "downloads": "डाउनलोड",
    "downloadAndroid": "Android के लिए डाउनलोड",
    "downloadWindows": "Windows के लिए डाउनलोड",
    "harmonyOS": "HarmonyOS संस्करण",
    "macOS": "macOS संस्करण",
    "comingSoon": "जल्द आ रहा है",
    "legal": "कानूनी",
    "terms": "शर्तें",
    "privacy": "गोपनीयता",
    "myAccount": "मेरा खाता"
  },
  "ur": {
    "language": "زبان",
    "chooseLanguage": "زبان منتخب کریں",
    "systemLanguage": "سسٹم زبان",
    "systemLanguageDescription": "وہ زبان منتخب کریں جو BridgeX مینیو، اکاؤنٹ رسائی، اور ترتیبات کے لیے استعمال کرے گا۔",
    "accountAccess": "اکاؤنٹ تک رسائی",
    "protectedOrderTrust": "محفوظ آرڈرز معتبر اکاؤنٹ سے شروع ہوتے ہیں۔",
    "signIn": "سائن ان",
    "createAccount": "اکاؤنٹ بنائیں",
    "displayName": "ظاہری نام",
    "emailAddress": "ای میل ایڈریس",
    "password": "پاس ورڈ",
    "continueWithGoogle": "Google کے ساتھ جاری رکھیں",
    "orUseEmail": "یا ای میل استعمال کریں",
    "signInSecurely": "محفوظ طریقے سے سائن ان کریں",
    "createSecureAccount": "محفوظ اکاؤنٹ بنائیں",
    "browseAsGuest": "مہمان کی حیثیت سے براؤز کریں",
    "emailConfirmation": "پہلے سائن ان سے قبل اپنی ای میل کی تصدیق کریں۔",
    "marketplace": "مارکیٹ پلیس",
    "howItWorks": "یہ کیسے کام کرتا ہے",
    "safety": "حفاظت",
    "contact": "رابطہ",
    "listSpace": "جگہ فہرست کریں",
    "postItem": "آئٹم پوسٹ کریں",
    "settings": "ترتیبات",
    "saveProfile": "پروفائل محفوظ کریں",
    "downloads": "ڈاؤن لوڈز",
    "downloadAndroid": "Android کے لیے ڈاؤن لوڈ کریں",
    "downloadWindows": "Windows کے لیے ڈاؤن لوڈ کریں",
    "harmonyOS": "HarmonyOS ورژن",
    "macOS": "macOS ورژن",
    "comingSoon": "جلد آ رہا ہے",
    "legal": "قانونی",
    "terms": "شرائط",
    "privacy": "رازداری",
    "myAccount": "میرا اکاؤنٹ"
  }
} as const;
export type TranslationKey = keyof typeof TRANSLATIONS.en;

export const isSystemLanguage = (value: unknown): value is SystemLanguage => LANGUAGE_OPTIONS.some(language => language.code === value);
export const translationFor = (language: SystemLanguage, key: TranslationKey) => TRANSLATIONS[language][key] || TRANSLATIONS.en[key];
