import { Brand } from "@/components/bridgex/Brand";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { supabase } from "@/lib/supabase";
import { ArrowLeft, CheckCircle2, Eye, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useLocation } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";

export default function Access() {
  const { isAuthenticated, loading } = useAuth(); const [, setLocation] = useLocation();
  const [email, setEmail] = useState(""); const [notice, setNotice] = useState(""); const [sending, setSending] = useState(false);
  useEffect(() => { if (!loading && isAuthenticated) setLocation("/onboarding"); }, [isAuthenticated, loading, setLocation]);
  const sendLink = async () => { setNotice(""); setSending(true); const { error } = await supabase.auth.signInWithOtp({ email, options: { emailRedirectTo: `${window.location.origin}/onboarding` } }); setSending(false); setNotice(error ? error.message : "Check your email for the secure BridgeX sign-in link."); };
  return <main className="grid min-h-screen bg-[#f7f5ef] lg:grid-cols-[0.9fr_1.1fr]"><section className="hidden bg-[#172126] p-10 text-[#f7f5ef] lg:flex lg:flex-col"><Brand className="[&>span:last-child]:text-[#f7f5ef]" /><div className="my-auto max-w-md"><span className="grid size-12 place-items-center rounded-2xl bg-[#2d8d62] text-white"><ShieldCheck className="size-6" /></span><h1 className="mt-7 font-display text-5xl font-bold leading-tight tracking-[-0.05em]">Protected orders start with a trusted account.</h1><p className="mt-5 text-sm leading-7 text-[#c3d0c9]">Use a verified email account to securely enter BridgeX.</p></div></section><section className="flex items-center justify-center px-5 py-10"><div className="w-full max-w-[440px]"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-[#176447]"><ArrowLeft className="size-4" />Back to BridgeX</Link><div className="mt-9 rounded-3xl border border-[#172126]/8 bg-white p-7 sm:p-8"><div className="grid size-11 place-items-center rounded-2xl bg-[#dff5ea] text-[#176447]"><ShieldCheck className="size-5" /></div><p className="mt-6 text-xs font-bold uppercase tracking-[0.16em] text-[#2d8d62]">Account access</p><h2 className="mt-2 font-display text-3xl font-bold tracking-[-0.05em]">Welcome to BridgeX.</h2><p className="mt-3 text-sm leading-6 text-[#657275]">Enter your email. We will send a secure one-time sign-in link; new emails create an account automatically.</p><Input className="mt-6 h-11 rounded-xl" type="email" placeholder="you@example.com" value={email} onChange={(e) => setEmail(e.target.value)} /><Button disabled={sending || !email} onClick={sendLink} className="mt-3 h-11 w-full rounded-xl bg-[#172126] font-bold">{sending ? "Sending secure link…" : "Send secure sign-in link"}</Button>{notice && <p className="mt-3 text-sm text-[#176447]">{notice}</p>}<Button onClick={() => setLocation("/marketplace?guest=1")} variant="outline" className="mt-4 h-11 w-full rounded-xl bg-white font-bold"><Eye className="mr-2 size-4" />Browse as guest</Button><div className="mt-5 rounded-xl bg-[#f4faf5] p-3 text-xs leading-5 text-[#526063]"><CheckCircle2 className="mr-1 inline size-3.5 text-[#2d8d62]" />Guest access can browse the marketplace. Posting, offers, orders, messages, verification, and wallet actions require secure sign-in.</div></div></div></section></main>;
}
