import { Brand } from "@/components/bridgex/Brand";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { ArrowLeft, ArrowRight, CheckCircle2, Eye, ShieldCheck } from "lucide-react";
import { useEffect } from "react";
import { Link, useLocation } from "wouter";

export default function Access() {
  const { isAuthenticated, loading } = useAuth(); const [, setLocation] = useLocation();
  useEffect(() => { if (!loading && isAuthenticated) setLocation("/onboarding"); }, [isAuthenticated, loading, setLocation]);
  return <main className="grid min-h-screen bg-[#f7f5ef] lg:grid-cols-[0.9fr_1.1fr]"><section className="hidden bg-[#172126] p-10 text-[#f7f5ef] lg:flex lg:flex-col"><Brand className="[&>span:last-child]:text-[#f7f5ef]" /><div className="my-auto max-w-md"><span className="grid size-12 place-items-center rounded-2xl bg-[#2d8d62] text-white"><ShieldCheck className="size-6" /></span><h1 className="mt-7 font-display text-5xl font-bold leading-tight tracking-[-0.05em]">Protected orders start with a trusted account.</h1><p className="mt-5 text-sm leading-7 text-[#c3d0c9]">Sign in securely, complete your profile and verification, then post or accept delivery work with verified members.</p><div className="mt-8 grid gap-3">{["Sign in or create your account", "Verify email, mobile number, and identity", "Post, match, chat, and use escrow"].map((step, index) => <div key={step} className="flex items-center gap-3 text-sm text-[#d3ded7]"><span className="grid size-6 place-items-center rounded-full bg-[#2d8d62] text-xs font-bold text-white">{index + 1}</span>{step}</div>)}</div></div><p className="text-xs font-semibold text-[#91e7bc]">Bangladesh delivery · Verified profiles · Escrow-first orders</p></section><section className="flex items-center justify-center px-5 py-10"><div className="w-full max-w-[440px]"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-[#176447]"><ArrowLeft className="size-4" />Back to BridgeX</Link><div className="mt-8 lg:hidden"><Brand /></div><div className="mt-9 rounded-3xl border border-[#172126]/8 bg-white p-7 sm:p-8"><div className="grid size-11 place-items-center rounded-2xl bg-[#dff5ea] text-[#176447]"><ShieldCheck className="size-5" /></div><p className="mt-6 text-xs font-bold uppercase tracking-[0.16em] text-[#2d8d62]">Account access</p><h2 className="mt-2 font-display text-3xl font-bold tracking-[-0.05em]">Welcome to BridgeX.</h2><p className="mt-3 text-sm leading-6 text-[#657275]">Use secure sign-in to post, make offers, use escrow, and manage your delivery activity.</p><Button onClick={startLogin} className="mt-7 h-11 w-full rounded-xl bg-[#172126] font-bold">Secure sign in or create account<ArrowRight className="ml-2 size-4" /></Button><Button onClick={() => setLocation("/marketplace?guest=1")} variant="outline" className="mt-3 h-11 w-full rounded-xl bg-white font-bold"><Eye className="mr-2 size-4" />Browse as guest</Button><div className="mt-5 rounded-xl bg-[#f4faf5] p-3 text-xs leading-5 text-[#526063]"><CheckCircle2 className="mr-1 inline size-3.5 text-[#2d8d62]" />Guest access can browse the marketplace. Posting, offers, orders, messages, verification, and wallet actions require secure sign-in.</div><p className="mt-5 text-center text-xs leading-5 text-[#7a8787]">Email-password and direct Google sign-in are not shown until a verified authentication provider is connected, so no button leads to a non-functional flow.</p></div></div></section></main>;
}
