import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { supabase } from "@/lib/supabase";
import { ArrowLeft, MessageSquareText, Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";

type ChatMessage = { id: string; match_id: string; sender_id: string; body: string; created_at: string };
export default function AdminChats() {
  const [, setLocation] = useLocation(); const [messages, setMessages] = useState<ChatMessage[]>([]); const [query, setQuery] = useState(""); const [notice, setNotice] = useState("");
  useEffect(() => { void (async () => { const { data, error } = await supabase.from("match_messages").select("id,match_id,sender_id,body,created_at").order("created_at", { ascending: false }).limit(500); if (error) setNotice(error.message); else setMessages((data ?? []) as ChatMessage[]); })(); }, []);
  const visible = useMemo(() => messages.filter(message => `${message.match_id} ${message.sender_id} ${message.body}`.toLowerCase().includes(query.toLowerCase())), [messages, query]);
  return <main className="min-h-screen bg-[#f7f5ef] px-5 py-8 text-[#172126]"><div className="mx-auto max-w-5xl"><Button onClick={() => setLocation("/admin")} variant="outline" className="rounded-xl bg-white"><ArrowLeft className="mr-2 size-4" />Control panel</Button><div className="mt-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#2d8d62]">Administrator safety review</p><h1 className="mt-2 font-display text-4xl font-bold tracking-[-0.055em]">Matched deal conversations</h1><p className="mt-2 text-sm text-[#637073]">Messages remain private to matched members and authorized administrators. Use this view only for safety, disputes, and incident review.</p></div><MessageSquareText className="size-7 text-[#176447]" /></div><div className="mt-6 flex h-11 items-center gap-2 rounded-xl border border-[#172126]/10 bg-white px-3"><Search className="size-4 text-[#647174]" /><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search conversation ID, participant ID, or message text" className="h-auto border-0 bg-transparent p-0 shadow-none focus-visible:ring-0" /></div>{notice && <p className="mt-4 rounded-xl bg-[#f8e8e5] px-3 py-2 text-sm font-semibold text-[#9b4b3e]">{notice}</p>}<div className="mt-6 grid gap-3">{visible.length ? visible.map(message => <article key={message.id} className="rounded-2xl border border-[#172126]/8 bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#2d8d62]">Deal {message.match_id.slice(0, 8)}</p><p className="mt-1 text-xs text-[#6a7779]">Sender {message.sender_id.slice(0, 8)} · {new Date(message.created_at).toLocaleString()}</p></div></div><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-[#526063]">{message.body}</p></article>) : <p className="rounded-2xl bg-white p-6 text-sm text-[#647174]">No matched conversation messages fit this search.</p>}</div></div></main>;
}
