import PublicLayout from "@/components/bridgex/PublicLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ArrowRight, CalendarDays, CircleDollarSign, MapPin, MessageCircle, PackageCheck, Plane, Plus, ShieldCheck, Weight } from "lucide-react";
import { Link } from "wouter";

const feed = [
  { type: "Item request", title: "Small electronics order", route: "Shenzhen → Dhaka", details: "1.2 kg · Budget ৳ 8,500", action: "Make an offer", href: "/offer" },
  { type: "Carry space", title: "Carry space available", route: "Guangzhou → Chattogram", details: "4 kg · ৳ 850 / kg", action: "Send interest", href: "/create-request" },
  { type: "Item request", title: "Skincare gift set", route: "Dubai → Sylhet", details: "0.8 kg · Budget ৳ 5,700", action: "Make an offer", href: "/offer" },
];

export default function Home() {
  return <PublicLayout><main>
    <section className="border-b border-[#172126]/8 bg-[#eef5ef] px-5 py-4 lg:px-8"><div className="mx-auto flex max-w-[1344px] flex-wrap items-center justify-center gap-x-8 gap-y-2 text-sm font-bold text-[#365348]"><span className="inline-flex items-center gap-2"><ShieldCheck className="size-4 text-[#23784f]" />Every matched order uses protected escrow</span><Link href="/how-it-works" className="inline-flex items-center gap-1 text-[#176447]">See how it works <ArrowRight className="size-3.5" /></Link></div></section>
    <section className="px-5 pb-12 pt-10 lg:px-8 lg:pb-16 lg:pt-14"><div className="mx-auto grid max-w-[1120px] gap-9 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#2d8d62]">Bangladesh carry marketplace</p><h1 className="mt-4 font-display text-5xl font-bold leading-[0.95] tracking-[-0.065em] sm:text-6xl">Post it. Match it.<br /><span className="text-[#2d8d62]">Bring it home.</span></h1><p className="mt-5 max-w-xl text-base leading-7 text-[#526063]">A focused place for people in Bangladesh to post what they need and travelers to post the space they have. Compare, chat, and use escrow when you match.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/marketplace"><Button variant="outline" className="h-11 rounded-xl bg-white font-bold">View marketplace <ArrowRight className="ml-2 size-4" /></Button></Link><Link href="/dashboard"><Button variant="ghost" className="h-11 rounded-xl font-bold text-[#176447]">My activity</Button></Link></div></div><div className="rounded-[2rem] border border-[#172126]/8 bg-white p-5 shadow-[0_18px_45px_rgba(32,45,41,0.08)] sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#2d8d62]">Create a post</p><h2 className="mt-1 text-xl font-bold">What would you like to do?</h2></div><span className="grid size-10 place-items-center rounded-2xl bg-[#e7f4ea] text-[#176447]"><Plus className="size-5" /></span></div><div className="mt-5 grid gap-3"><Link href="/create-request" className="group rounded-2xl border border-[#172126]/10 bg-[#f8f7f2] p-5 transition hover:border-[#2d8d62]/40 hover:bg-[#f0f8f2]"><div className="flex items-center justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-[#dff5ea] text-[#176447]"><PackageCheck className="size-5" /></span><ArrowRight className="size-5 text-[#2d8d62] transition group-hover:translate-x-1" /></div><p className="mt-4 text-lg font-bold">I need an item</p><p className="mt-1 text-sm leading-6 text-[#637073]">Post an item, budget, weight, and Bangladesh delivery address.</p></Link><Link href="/create-listing" className="group rounded-2xl bg-[#172126] p-5 text-[#f7f5ef] transition hover:bg-[#24343a]"><div className="flex items-center justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-[#2d8d62] text-white"><Plane className="size-5" /></span><ArrowRight className="size-5 text-[#91e7bc] transition group-hover:translate-x-1" /></div><p className="mt-4 text-lg font-bold">I have carry space</p><p className="mt-1 text-sm leading-6 text-[#c3d0c9]">Post your route, date, available weight, and price.</p></Link></div></div></div></section>
    <section className="border-y border-[#172126]/8 bg-[#f3f1ea] px-5 py-10 lg:px-8 lg:py-14"><div className="mx-auto max-w-[1120px]"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#2d8d62]">Marketplace feed</p><h2 className="mt-2 font-display text-3xl font-bold tracking-[-0.045em]">Recent posts into Bangladesh.</h2></div><Link href="/marketplace" className="inline-flex items-center gap-2 text-sm font-bold text-[#176447]">Open full feed <ArrowRight className="size-4" /></Link></div><div className="mt-7 grid gap-3 md:grid-cols-3">{feed.map((post, index) => <article key={post.title} className="rounded-2xl border border-[#172126]/8 bg-white p-5"><div className="flex items-center justify-between"><Badge className={`rounded-full text-[10px] font-bold uppercase tracking-[0.08em] ${index === 1 ? "bg-[#172126] text-white hover:bg-[#172126]" : "bg-[#e7f4ea] text-[#23784f] hover:bg-[#e7f4ea]"}`}>{post.type}</Badge><span className="inline-flex items-center gap-1 text-xs font-bold text-[#23784f]"><ShieldCheck className="size-3.5" />Verified only</span></div><h3 className="mt-5 text-lg font-bold tracking-[-0.025em]">{post.title}</h3><div className="mt-4 grid gap-2 text-sm text-[#617073]"><p className="flex items-center gap-2"><Plane className="size-4 text-[#2d8d62]" />{post.route}</p><p className="flex items-center gap-2"><Weight className="size-4 text-[#2d8d62]" />{post.details}</p></div><Link href={post.href} className="mt-5 flex"><Button variant="outline" className="h-10 w-full rounded-xl bg-[#fbfaf7] font-bold">{post.action}</Button></Link></article>)}</div></div></section>
    <section className="px-5 py-10 lg:px-8 lg:py-14"><div className="mx-auto grid max-w-[1120px] gap-4 rounded-3xl bg-[#172126] p-6 text-[#f7f5ef] sm:grid-cols-[auto_1fr_auto] sm:items-center sm:p-8"><span className="grid size-12 place-items-center rounded-2xl bg-[#2d8d62]"><CircleDollarSign className="size-6" /></span><div><h2 className="text-xl font-bold">No direct payment to a traveler.</h2><p className="mt-1 text-sm leading-6 text-[#c3d0c9]">Select a match, fund escrow, confirm delivery, then payment is released.</p></div><Link href="/how-it-works"><Button className="rounded-xl bg-[#91e7bc] font-bold text-[#172126] hover:bg-[#b7efcc]">Escrow flow <ArrowRight className="ml-1 size-4" /></Button></Link></div></section>
  </main></PublicLayout>;
}
