import PublicLayout from "@/components/bridgex/PublicLayout";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { AlertTriangle, ArrowRight, FileCheck2, LockKeyhole, Mail, ShieldCheck, UserRoundCheck } from "lucide-react";
import { Link } from "wouter";

const flow = [
  ["1", "Offer", "A traveler sends a route, capacity, estimated arrival, and service proposal for a live item request."],
  ["2", "Protected acceptance", "The sender selects a suitable traveler after both parties have completed the required information and acknowledgement steps."],
  ["3", "Pickup", "The members arrange the lawful pickup or handoff using the protected details shared after acceptance."],
  ["4", "Handoff", "The traveler records receipt of the accurately described goods at the agreed handoff point."],
  ["5", "Transit", "The traveler updates progress while following applicable carrier, declaration, customs, and local rules."],
  ["6", "Delivered", "The recipient confirms that the goods arrived as agreed."],
  ["7", "Completed", "The protected order record stays available for support, review, and dispute handling."],
];

const faqs = [
  ["What does BridgeX do?", "BridgeX is a marketplace for members to discover capacity, document arrangements, and use protected order workflows. It does not sell your item, act as the traveler or carrier, serve as a customs broker, or guarantee customs clearance, delivery, or another member’s performance."],
  ["Who can list a flight, train, or cargo route?", "Members who complete the required profile information can publish available flight, train, or cargo capacity for domestic and cross-border routes, subject to BridgeX’s terms and acceptable-item rules."],
  ["Are taxes, duties, and customs fees included?", "No. Taxes, duties, declarations, import or export charges, and other government or carrier fees depend on the route, item, value, quantity, purpose, and relevant rules. Members must check the applicable rules before agreeing to a handoff. A traveler may reflect expected lawful costs in an offer, but BridgeX does not promise duty-free treatment or customs clearance."],
  ["Can an item be called personal luggage to avoid customs rules?", "No. Calling an item personal, a gift, or luggage does not automatically remove declaration, duty, tax, quantity, value, commercial-use, or other legal obligations. The sender must describe the item, quantity, value, and purpose accurately, and the traveler must make any required truthful declaration."],
  ["What items are not allowed?", "Do not post, offer, or carry unlawful, stolen, counterfeit, dangerous, explosive, weapon-related, controlled, undeclared where required, restricted, or prohibited items. This includes anything prohibited by an origin, transit, destination, carrier, or local rule. BridgeX may remove, restrict, cancel, or report activity where appropriate."],
  ["What if the actual item differs from the post?", "A sender must not conceal, substitute, relabel, or materially change an item after a traveler has relied on the post. The traveler may refuse the item or handoff. BridgeX may cancel the arrangement, preserve relevant records, restrict the account, and cooperate with competent authorities where required or permitted by law."],
  ["Are domestic routes supported?", "Yes. BridgeX supports routes within the same country as well as cross-border routes. Members remain responsible for local transport, consumer, item, tax, and carrier requirements on domestic routes."],
  ["What verification can I submit?", "You can submit a National ID, passport, or student ID where applicable. Student submissions can include university name and address. Email and mobile-number confirmation are separate profile checks."],
  ["What happens when there is a problem?", "Open a dispute from the relevant order before completion and submit a safety report for suspected fraud, threats, prohibited goods, or serious misconduct. Contact emergency services, police, customs, or another competent authority directly when immediate danger or an official response is needed."],
];

function Intro({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) {
  return <section className="border-b border-[#172126]/8 bg-[#e8f3e9] px-5 py-16 lg:px-8 lg:py-20"><div className="mx-auto max-w-[920px]"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#23784f]">{eyebrow}</p><h1 className="mt-4 font-display text-5xl font-bold tracking-[-0.06em] sm:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#526063]">{copy}</p></div></section>;
}

export function HowItWorks() {
  return <PublicLayout><Intro eyebrow="The BridgeX method" title="Every protected handoff has a clear next step." copy="BridgeX gives both sides a documented view of the route, acknowledgement, handoff, delivery, and order-completion journey." /><section className="px-5 py-16 lg:px-8 lg:py-24"><div className="mx-auto max-w-[920px] space-y-4">{flow.map(([number, title, copy]) => <article key={number} className="grid gap-4 rounded-3xl border border-[#172126]/8 bg-white p-6 sm:grid-cols-[72px_1fr] sm:p-8"><span className="font-display text-4xl font-bold text-[#2d8d62]">{number}</span><div><h2 className="text-xl font-bold tracking-[-0.03em]">{title}</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[#627073]">{copy}</p></div></article>)}</div><div className="mx-auto mt-12 max-w-[920px] rounded-3xl bg-[#172126] p-8 text-[#f7f5ef] sm:p-10"><LockKeyhole className="size-7 text-[#91e7bc]" /><h2 className="mt-5 font-display text-3xl font-bold tracking-[-0.04em]">Clarity and records support safer decisions.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#c3d0c9]">BridgeX records the route, terms acknowledgements, status changes, and protected communication. It does not replace customs, carrier, police, insurance, or other official processes.</p><Link href="/access"><Button className="mt-7 rounded-xl bg-[#91e7bc] font-bold text-[#172126] hover:bg-[#b6f3cf]">Start a protected order <ArrowRight className="ml-1 size-4" /></Button></Link></div></section></PublicLayout>;
}

export function SafetyPage() {
  const cards = [[UserRoundCheck, "Account verification", "Identity-document review, plus separate email and mobile-verification signals, make account status visible. Verification is a trust signal, not a guarantee."], [ShieldCheck, "Accurate item declarations", "Senders must state the item, quantity, value, route, and purpose accurately. A traveler may refuse any item that appears concealed, substituted, prohibited, or materially different from the post."], [FileCheck2, "Documented protected workflow", "Offers, acceptance acknowledgements, status updates, chat, payment records, and disputes stay associated with the order rather than an external conversation."], [AlertTriangle, "Customs, duty, and reporting responsibility", "Members must follow relevant domestic or cross-border laws, carrier rules, declarations, taxes, and duties. BridgeX does not promise duty-free treatment or customs clearance."]];
  return <PublicLayout><Intro eyebrow="Safety & trust" title="Clear responsibility before every handoff." copy="BridgeX helps members discover capacity, document arrangements, and report safety concerns. It does not replace customs, carrier, police, emergency, or other official processes." /><section className="px-5 py-16 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-[1100px] gap-4 md:grid-cols-2">{cards.map(([Icon, title, copy]) => <article key={title as string} className="rounded-3xl border border-[#172126]/8 bg-white p-7"><div className="grid size-11 place-items-center rounded-2xl bg-[#dff5ea] text-[#176447]"><Icon className="size-5" /></div><h2 className="mt-5 text-xl font-bold">{title as string}</h2><p className="mt-3 text-sm leading-6 text-[#657275]">{copy as string}</p></article>)}</div><div className="mx-auto mt-12 max-w-[1100px] rounded-3xl border border-[#e4c984] bg-[#fff9ea] p-7"><p className="font-bold text-[#6e5624]">Before you post, offer, or accept</p><p className="mt-2 max-w-3xl text-sm leading-6 text-[#77683f]">Do not send or carry an item unless its description is accurate and you have checked applicable domestic or cross-border rules. Never use an inaccurate “personal item,” “gift,” or luggage label to avoid a lawful declaration. When a risk requires official help, contact the appropriate authorities directly and use BridgeX reporting to preserve the platform record.</p></div></section></PublicLayout>;
}

export function FaqPage() {
  return <PublicLayout><Intro eyebrow="Questions, answered" title="Clear rules before you arrange a handoff." copy="Find essential answers about domestic and cross-border routes, customs, duties, prohibited items, verification, safety, and BridgeX’s platform role." /><section className="px-5 py-16 lg:px-8 lg:py-24"><div className="mx-auto max-w-[800px]"><Accordion type="single" collapsible className="rounded-3xl border border-[#172126]/8 bg-white px-6">{faqs.map(([question, answer], index) => <AccordionItem value={`faq-${index}`} key={question}><AccordionTrigger className="py-6 text-left text-base font-bold hover:no-underline">{question}</AccordionTrigger><AccordionContent className="pb-6 text-sm leading-7 text-[#657275]">{answer}</AccordionContent></AccordionItem>)}</Accordion><div className="mt-10 rounded-3xl bg-[#dff0e6] p-7"><Mail className="size-6 text-[#176447]" /><h2 className="mt-4 text-xl font-bold">Still need help?</h2><p className="mt-2 text-sm text-[#526063]">Contact BridgeX support with an order reference and concise context. Use the in-order report option for safety concerns.</p><Link href="/contact" className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#176447]">Contact support <ArrowRight className="size-4" /></Link></div></div></section></PublicLayout>;
}

const legalCopy = {
  terms: ["Terms & Conditions", "These terms govern access to BridgeX marketplace tools for domestic and cross-border carrying arrangements. They explain member responsibilities, required acknowledgements, safety actions, and the limits of the platform."],
  privacy: ["Privacy Policy", "This policy explains the account, verification, order, support, and safety information BridgeX processes to operate the platform."],
};

const legalSections = {
  terms: [
    ["BridgeX platform role", "BridgeX provides marketplace discovery, capacity matching, documentation, communication, payment-status coordination, and safety tools for domestic and cross-border arrangements. Except where BridgeX expressly states otherwise in writing, BridgeX is not the buyer, seller, sender, traveler, carrier, freight forwarder, customs broker, insurer, or guarantor of customs clearance or delivery. Members make their own arrangements and remain responsible for their own actions."],
    ["Required terms acknowledgements", "Before publishing a request or capacity listing, making an offer, showing interest, or starting protected acceptance, members must actively acknowledge the current Terms & Conditions. BridgeX records the acknowledgement version and time with the related workflow action. Acknowledgement does not remove a member’s legal rights that cannot lawfully be waived."],
    ["Truthful items and sender declaration", "A sender must accurately describe each item’s nature, quantity, value, condition, origin, route, intended purpose, and handling needs. A sender must not conceal, substitute, relabel, understate, or materially alter an item after another member has relied on the post. If an item is illegal, restricted, dangerous, counterfeit, undeclared where required, or materially different from the post, the traveler may refuse it; BridgeX may remove the post, cancel the arrangement, restrict the account, preserve records, and cooperate with competent authorities where required or permitted by law."],
    ["Customs, duties, taxes, and declarations", "Customs duties, taxes, import or export charges, declarations, carrier fees, limits, and permits may apply based on the item, route, value, quantity, purpose, and relevant rules. Calling an item personal luggage, a gift, or a personal item does not automatically remove these obligations. Senders and travelers must independently check applicable rules, make truthful declarations where required, and pay or arrange lawful charges for which they are responsible. BridgeX does not promise duty-free treatment, customs clearance, or a particular tax result."],
    ["Prohibited and restricted items", "Members must not use BridgeX for goods or conduct prohibited by applicable origin, transit, destination, carrier, or local rules. This includes unlawful, stolen, counterfeit, dangerous, explosive, weapon-related, controlled, restricted, or improperly declared goods. Members must also comply with applicable transport, aviation, train, cargo, safety, consumer, and sanctions rules. When in doubt, do not post, offer, send, or carry the item until a qualified official source confirms it is permitted."],
    ["Choosing members and keeping records", "Verification is a trust signal, not a guarantee of performance. Members should compare route, capacity, communication, order history where available, and visible verification status. For higher-value or sensitive items, BridgeX strongly recommends selecting a Verified member, keeping communications in the protected deal, and retaining handoff and delivery evidence."],
    ["Damage, loss, disputes, and safety reports", "Package goods appropriately and record item condition, packaging, handoff, and delivery evidence. If damage, loss, fraud, harassment, or another safety issue occurs, use the in-platform report or dispute process promptly and preserve original evidence. BridgeX may review available order records, messages, media, verification status, and reports, but does not guarantee a specific dispute outcome, recovery, insurance payment, or delivery result. Contact emergency services, police, customs, or another competent authority directly when an immediate official response is needed."],
    ["Safety enforcement and lawful cooperation", "BridgeX may preserve relevant account, order, verification, message, media, acknowledgement, and safety-report records for fraud prevention, dispute handling, platform integrity, or legal obligations. Where legally required or permitted, BridgeX may cooperate with competent authorities through an appropriate lawful process. Members must not use the platform to threaten, defraud, conceal prohibited goods, or harm another person."],
    ["Account action and updates", "BridgeX may suspend, restrict, remove, or investigate accounts, responses, listings, and posts that breach these terms or create a safety risk. These terms may be updated as the platform, payment arrangements, regulations, or safety controls evolve. Continued use after an effective update means the member accepts the revised terms to the extent permitted by law."],
  ],
  privacy: [
    ["Information BridgeX processes", "BridgeX may process account details, contact information, profile and verification submissions, post content, media, order records, protected-deal messages, support enquiries, safety reports, device or session information, and operational logs. National ID, passport, and student documents are handled through the restricted verification workflow rather than public posts."],
    ["Why information is used", "Information is used to create and protect accounts, verify identity where requested, publish marketplace posts, form protected matches, share required counterpart contact details after acceptance, coordinate orders, respond to enquiries, prevent fraud or abuse, resolve disputes, meet legal obligations, and improve platform reliability."],
    ["When information is shared", "Public posts show only the information necessary to discover a listing, including the member display name and verification state. Private delivery contact details are shared only with the matched counterpart. BridgeX may use service providers that operate platform infrastructure and may disclose information to authorized administrators or competent authorities when necessary for safety, fraud prevention, or a valid legal requirement."],
    ["Retention and media cleanup", "BridgeX retains information for as long as reasonably needed for the purposes described here, including active account, order, support, safety, and legal-record needs. Released-post photos and videos are designed to be cleared from the original post storage after sender-confirmed completion, while protected order history is retained for support and administration."],
    ["Security and your choices", "BridgeX uses access controls and restricted workflows for sensitive data, but no internet service can promise absolute security. Members should protect account credentials, avoid sharing unnecessary identity data in public fields, keep information accurate, and contact BridgeX through the Contact page for privacy, support, or account questions."],
  ],
};

export function StandardPage({ type }: { type: "about" | "contact" | "terms" | "privacy" }) {
  const data = type === "about" ? ["About BridgeX", "BridgeX is building a more legible way for people worldwide to coordinate domestic and cross-border item delivery with travelers and cargo carriers."] : type === "contact" ? ["Contact BridgeX", "Need guidance on a listing, order, verification, or safety concern? Our support team is ready to help you navigate the marketplace."] : legalCopy[type];
  const sections = type === "terms" || type === "privacy" ? legalSections[type] : [];
  return <PublicLayout><Intro eyebrow={type === "about" ? "Our purpose" : type === "contact" ? "Support" : "BridgeX legal"} title={data[0]} copy={data[1]} /><section className="px-5 py-16 lg:px-8 lg:py-24"><div className="mx-auto max-w-[800px] rounded-3xl border border-[#172126]/8 bg-white p-7 sm:p-10">{type === "contact" ? <><Mail className="size-7 text-[#176447]" /><h2 className="mt-5 text-2xl font-bold">Start with the context we need.</h2><p className="mt-3 leading-7 text-[#627073]">Include your BridgeX order reference, the email associated with your account, and a concise description of the issue. For safety concerns, use the in-order report option as well.</p><Link href="/contact"><Button className="mt-7 rounded-xl bg-[#172126] font-bold">Contact support</Button></Link></> : type === "terms" || type === "privacy" ? <><p className="rounded-2xl bg-[#fff9ea] p-4 text-sm leading-6 text-[#77683f]">Read these platform terms and privacy information before using BridgeX. For an issue involving immediate danger or crime, contact local emergency or law-enforcement services directly.</p><div className="mt-7 space-y-8">{sections.map(([heading, copy]) => <section key={heading}><h2 className="text-xl font-bold">{heading}</h2><p className="mt-3 text-sm leading-7 text-[#627073]">{copy}</p></section>)}</div></> : <><h2 className="text-2xl font-bold">A marketplace designed around responsibility.</h2><div className="mt-5 space-y-4 text-sm leading-7 text-[#627073]"><p>BridgeX provides marketplace coordination and does not replace customs rules, carrier policies, local laws, or official authorities. Participants remain responsible for accurate posts and lawful items.</p><p>Account verification, terms acknowledgement, protected orders, order-based communication, reporting, and dispute handling work together to support safer decisions.</p></div><Link href="/how-it-works" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#176447]">See how BridgeX works <ArrowRight className="size-4" /></Link></>}</div></section></PublicLayout>;
}
