import PublicLayout from "@/components/bridgex/PublicLayout";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { AlertTriangle, ArrowRight, BadgeCheck, CheckCircle2, FileCheck2, LockKeyhole, Mail, ShieldCheck, UserRoundCheck } from "lucide-react";
import { Link } from "wouter";

const flow = [
  ["1", "Match", "Senders publish a request or travelers publish capacity. Both can explore route, date, category, and delivery details before moving forward."],
  ["2", "Offer & select", "Travelers make an offer with a service price and delivery estimate. The sender selects a suitable verified traveler."],
  ["3", "Deposit to escrow", "The sender funds the agreed order total through BridgeX escrow. Direct payment between parties is not used in the order flow."],
  ["4", "Purchase & carry", "The traveler purchases or receives the agreed item, then carries it through the listed flight or cargo route."],
  ["5", "Confirm & release", "After delivery confirmation, BridgeX releases the agreed traveler payment. Any issue can be raised before release."],
];

const faqs = [
  ["What does BridgeX protect?", "BridgeX makes the payment lifecycle explicit: agreed order funds are held in escrow, then released only after delivery confirmation. It also keeps the discussion, status changes, and disputes tied to the order."],
  ["Who can list a flight or cargo route?", "Users who complete profile and identity verification can publish their available travel or cargo capacity, subject to the platform’s terms and acceptable-item rules."],
  ["What verification can I submit?", "You can submit a Bangladesh National ID, passport, or student ID. Student submissions can include university name and address. Email and mobile-number confirmation are separate profile checks."],
  ["How do I choose a traveler?", "Compare the proposed amount, listed route and timing, available capacity, and the visible verification status before accepting an offer."],
  ["What happens when there is a problem?", "Open a dispute from the relevant order before funds are released. The order’s payment status is held while the case is reviewed."],
];

function Intro({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) {
  return <section className="border-b border-[#172126]/8 bg-[#e8f3e9] px-5 py-16 lg:px-8 lg:py-20"><div className="mx-auto max-w-[920px]"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#23784f]">{eyebrow}</p><h1 className="mt-4 font-display text-5xl font-bold tracking-[-0.06em] sm:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#526063]">{copy}</p></div></section>;
}

export function HowItWorks() { return <PublicLayout><Intro eyebrow="The BridgeX method" title="Every protected handoff has a clear next step." copy="BridgeX gives both sides a shared view of the journey—matching, funding, purchase, travel, delivery, and payment release." /><section className="px-5 py-16 lg:px-8 lg:py-24"><div className="mx-auto max-w-[920px] space-y-4">{flow.map(([number, title, copy]) => <article key={number} className="grid gap-4 rounded-3xl border border-[#172126]/8 bg-white p-6 sm:grid-cols-[72px_1fr] sm:p-8"><span className="font-display text-4xl font-bold text-[#2d8d62]">{number}</span><div><h2 className="text-xl font-bold tracking-[-0.03em]">{title}</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[#627073]">{copy}</p></div></article>)}</div><div className="mx-auto mt-12 max-w-[920px] rounded-3xl bg-[#172126] p-8 text-[#f7f5ef] sm:p-10"><LockKeyhole className="size-7 text-[#91e7bc]" /><h2 className="mt-5 font-display text-3xl font-bold tracking-[-0.04em]">Escrow is the bridge between confidence and delivery.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#c3d0c9]">Funds are deposited into BridgeX after a sender selects an offer. They remain on hold while the traveler completes the order and are released only after delivery confirmation.</p><Button className="mt-7 rounded-xl bg-[#91e7bc] font-bold text-[#172126] hover:bg-[#b6f3cf]" onClick={startLogin}>Start a protected order <ArrowRight className="ml-1 size-4" /></Button></div></section></PublicLayout>; }

export function SafetyPage() { const cards = [[UserRoundCheck,"Account verification","Identity document review, plus separate email and mobile-verification signals, make account status visible."],[ShieldCheck,"Escrow protection","Direct payment is kept out of the standard order lifecycle so order funding and release stay traceable."],[FileCheck2,"Order record","Offers, escrow status, delivery progress, chat, and disputes belong to the order rather than an external conversation."],[AlertTriangle,"Report & dispute tools","Users can report suspicious behavior and raise an order dispute before the associated funds are released."]]; return <PublicLayout><Intro eyebrow="Safety & trust" title="Trust is built into the journey, not bolted on later." copy="BridgeX combines verification, transparent payment stages, order-based communication, and moderation workflows to create an easier-to-understand cross-border delivery experience." /><section className="px-5 py-16 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-[1100px] gap-4 md:grid-cols-2">{cards.map(([Icon, title, copy]) => <article key={title as string} className="rounded-3xl border border-[#172126]/8 bg-white p-7"><div className="grid size-11 place-items-center rounded-2xl bg-[#dff5ea] text-[#176447]"><Icon className="size-5" /></div><h2 className="mt-5 text-xl font-bold">{title as string}</h2><p className="mt-3 text-sm leading-6 text-[#657275]">{copy as string}</p></article>)}</div><div className="mx-auto mt-12 max-w-[1100px] rounded-3xl border border-[#e4c984] bg-[#fff9ea] p-7"><p className="font-bold text-[#6e5624]">Before you proceed</p><p className="mt-2 max-w-3xl text-sm leading-6 text-[#77683f]">Never share login credentials, make direct off-platform payments, or send restricted goods. Read the item guidelines and use the built-in report flow when something seems unsafe.</p></div></section></PublicLayout>; }

export function FaqPage() { return <PublicLayout><Intro eyebrow="Questions, answered" title="A clearer way to cross borders." copy="Find the main answers about profiles, listings, payment protection, verification, and order support." /><section className="px-5 py-16 lg:px-8 lg:py-24"><div className="mx-auto max-w-[800px]"><Accordion type="single" collapsible className="rounded-3xl border border-[#172126]/8 bg-white px-6">{faqs.map(([question, answer], index) => <AccordionItem value={`faq-${index}`} key={question}><AccordionTrigger className="py-6 text-left text-base font-bold hover:no-underline">{question}</AccordionTrigger><AccordionContent className="pb-6 text-sm leading-7 text-[#657275]">{answer}</AccordionContent></AccordionItem>)}</Accordion><div className="mt-10 rounded-3xl bg-[#dff0e6] p-7"><Mail className="size-6 text-[#176447]" /><h2 className="mt-4 text-xl font-bold">Still need help?</h2><p className="mt-2 text-sm text-[#526063]">Contact the BridgeX support team with an order reference for the fastest help.</p><Link href="/contact" className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#176447]">Contact support <ArrowRight className="size-4" /></Link></div></div></section></PublicLayout>; }

const legalCopy = { terms: ["Terms & conditions", "These platform terms describe how BridgeX provides marketplace tools for sending, carrying, and delivering eligible items. Use of the marketplace is subject to account verification, acceptable-item rules, escrow payment conditions, and local requirements."], privacy: ["Privacy policy", "This policy describes the information BridgeX needs to operate profile verification, order coordination, payment records, customer support, and safety controls. Identity documents are submitted only through the protected verification workflow."] };
export function StandardPage({ type }: { type: "about" | "contact" | "terms" | "privacy" }) { const data = type === "about" ? ["About BridgeX", "BridgeX is building a more legible way for people in Bangladesh to coordinate cross-border item delivery with travelers and cargo carriers. The platform centers verified participation and an escrow-first payment flow."] : type === "contact" ? ["Contact BridgeX", "Need guidance on a listing, order, verification, or safety concern? Our support team is ready to help you navigate the marketplace."] : legalCopy[type]; return <PublicLayout><Intro eyebrow={type === "about" ? "Our purpose" : type === "contact" ? "Support" : "BridgeX legal"} title={data[0]} copy={data[1]} /><section className="px-5 py-16 lg:px-8 lg:py-24"><div className="mx-auto max-w-[800px] rounded-3xl border border-[#172126]/8 bg-white p-7 sm:p-10">{type === "contact" ? <><Mail className="size-7 text-[#176447]" /><h2 className="mt-5 text-2xl font-bold">Start with the context we need.</h2><p className="mt-3 leading-7 text-[#627073]">Include your BridgeX order reference, the email associated with your account, and a concise description of the issue. For safety concerns, use the in-order report option as well.</p><Button className="mt-7 rounded-xl bg-[#172126] font-bold" onClick={() => window.location.href = "mailto:support@bridgex.market"}>Email support</Button></> : <><h2 className="text-2xl font-bold">{type === "about" ? "A marketplace designed around responsibility." : "Key principles"}</h2><div className="mt-5 space-y-4 text-sm leading-7 text-[#627073]"><p>BridgeX is designed to provide marketplace coordination rather than replace customs rules, airline policies, or local laws. Participants are responsible for the accuracy of their posts and the eligibility of items they arrange to carry.</p><p>Account verification, escrow, order-based communication, reporting, and dispute handling work together to support safer decisions. Complete terms and privacy disclosures should be reviewed and approved by qualified counsel before a public production launch.</p></div>{type === "about" && <Link href="/how-it-works" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#176447]">See how BridgeX works <ArrowRight className="size-4" /></Link>}</>}</div></section></PublicLayout>; }
