import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { supabase } from "@/lib/supabase";
import { Bell, CheckCheck, ExternalLink, LoaderCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "wouter";

type Notification = { id: string; title: string; body: string; link: string | null; read_at: string | null; created_at: string; type: string };
const PAGE_SIZE = 50;

export default function NotificationsPage() {
  const { user } = useAuth(); const [items, setItems] = useState<Notification[]>([]); const [loading, setLoading] = useState(true); const [loadingMore, setLoadingMore] = useState(false); const [hasMore, setHasMore] = useState(false); const [message, setMessage] = useState("");
  const load = async (offset = 0) => { if (!user) return; if (offset === 0) setLoading(true); else setLoadingMore(true); const { data, error } = await supabase.from("notifications").select("id,title,body,link,read_at,created_at,type").eq("user_id", user.id).order("created_at", { ascending: false }).range(offset, offset + PAGE_SIZE - 1); if (error) setMessage(error.message); else { const page = (data ?? []) as Notification[]; setItems(current => offset === 0 ? page : [...current, ...page]); setHasMore(page.length === PAGE_SIZE); } if (offset === 0) setLoading(false); else setLoadingMore(false); };
  useEffect(() => { void load(); }, [user?.id]);
  const markAllRead = async () => { if (!user) return; const { error } = await supabase.from("notifications").update({ read_at: new Date().toISOString() }).eq("user_id", user.id).is("read_at", null); if (error) setMessage(error.message); else { setItems(current => current.map(item => ({ ...item, read_at: item.read_at ?? new Date().toISOString() }))); setMessage("All notifications marked as read."); } };
  const markRead = async (item: Notification) => { if (item.read_at) return; const readAt = new Date().toISOString(); await supabase.from("notifications").update({ read_at: readAt }).eq("id", item.id); setItems(current => current.map(candidate => candidate.id === item.id ? { ...candidate, read_at: readAt } : candidate)); };
  return <DashboardLayout><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#2d8d62]">Member workspace</p><h1 className="mt-2 font-display text-4xl font-bold tracking-[-0.055em]">Updates & notifications</h1><p className="mt-2 text-sm text-[#637073]">All account, offer, payment, order, support, safety, and administrator updates appear here.</p></div><Button onClick={markAllRead} variant="outline" className="rounded-xl bg-white font-bold"><CheckCheck className="mr-2 size-4" />Mark all read</Button></div>{message && <p className="mt-5 rounded-xl bg-[#f4f2eb] px-3 py-2 text-sm font-semibold text-[#536164]">{message}</p>}<div className="mt-7 grid gap-3">{loading ? <div className="rounded-3xl bg-white p-7 text-sm font-semibold text-[#647174]">Loading updates…</div> : items.length ? items.map(item => <article key={item.id} className={`rounded-3xl border p-5 ${item.read_at ? "border-[#172126]/8 bg-white" : "border-[#2d8d62]/25 bg-[#eef8f0]"}`}><div className="flex items-start gap-3"><span className={`mt-0.5 grid size-9 shrink-0 place-items-center rounded-xl ${item.read_at ? "bg-[#f1eee6] text-[#637073]" : "bg-[#dff5ea] text-[#176447]"}`}><Bell className="size-4" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><h2 className="font-bold">{item.title}</h2><time className="text-xs font-semibold text-[#71807b]">{new Date(item.created_at).toLocaleString()}</time></div><p className="mt-2 text-sm leading-6 text-[#5b6769]">{item.body}</p>{item.link && <Link href={item.link} onClick={() => void markRead(item)} className="mt-3 inline-flex items-center gap-1 text-sm font-bold text-[#176447]">Open update <ExternalLink className="size-3.5" /></Link>}</div></div></article>) : <div className="rounded-3xl border border-dashed border-[#172126]/18 bg-white p-10 text-center"><Bell className="mx-auto size-8 text-[#2d8d62]" /><h2 className="mt-4 font-bold">No updates yet</h2><p className="mt-2 text-sm text-[#637073]">When a member responds to a post or an administrator updates your account, you will see it here.</p></div>}{hasMore && <div className="pt-2 text-center"><Button onClick={() => void load(items.length)} disabled={loadingMore} variant="outline" className="rounded-xl bg-white font-bold">{loadingMore ? <><LoaderCircle className="mr-2 size-4 animate-spin" />Loading more…</> : "Load more updates"}</Button></div>}</div></DashboardLayout>;
}
