import { Brand } from "@/components/bridgex/Brand";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { supabase } from "@/lib/supabase";
import { KeyRound, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { Link, useLocation } from "wouter";

export default function ResetPassword() {
  const [, setLocation] = useLocation(); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [notice, setNotice] = useState(""); const [failed, setFailed] = useState(false); const [saving, setSaving] = useState(false);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setNotice(""); setFailed(false); if (password.length < 8) { setFailed(true); return setNotice("Use a new password with at least 8 characters."); } if (password !== confirm) { setFailed(true); return setNotice("The two new passwords do not match."); } setSaving(true); const { error } = await supabase.auth.updateUser({ password }); setSaving(false); if (error) { setFailed(true); return setNotice("This reset link has expired or is invalid. Request a new secure reset email."); } setNotice("Your password was updated securely. You can now sign in."); setTimeout(() => setLocation("/access"), 1000); };
  return <main className="grid min-h-screen place-items-center bg-[#f7f5ef] px-5 py-10"><section className="w-full max-w-md rounded-3xl border border-[#172126]/8 bg-white p-7 sm:p-8"><Brand /><div className="mt-8 grid size-11 place-items-center rounded-2xl bg-[#dff5ea] text-[#176447]"><KeyRound className="size-5" /></div><p className="mt-5 text-xs font-bold uppercase tracking-[0.16em] text-[#2d8d62]">Secure password recovery</p><h1 className="mt-2 font-display text-3xl font-bold">Choose a new password.</h1><p className="mt-3 text-sm leading-6 text-[#637073]">This page only works from a recent password-reset email. BridgeX administrators cannot see your old or new password.</p><form onSubmit={save} className="mt-6 grid gap-3"><Input required type="password" autoComplete="new-password" minLength={8} placeholder="New password" value={password} onChange={event => setPassword(event.target.value)} className="h-11 rounded-xl" /><Input required type="password" autoComplete="new-password" minLength={8} placeholder="Confirm new password" value={confirm} onChange={event => setConfirm(event.target.value)} className="h-11 rounded-xl" /><Button disabled={saving} className="h-11 rounded-xl bg-[#172126] font-bold">{saving ? "Updating password…" : "Save new password"}</Button></form>{notice && <p className={`mt-4 rounded-xl px-3 py-2 text-sm font-semibold ${failed ? "bg-[#f8e8e5] text-[#9b4b3e]" : "bg-[#edf8f0] text-[#176447]"}`}>{notice}</p>}<div className="mt-6 flex items-center gap-2 text-xs text-[#637073]"><ShieldCheck className="size-3.5 text-[#2d8d62]" />Only the email account holder can use the reset link.</div><Link href="/access" className="mt-5 inline-flex text-sm font-bold text-[#176447]">Back to sign in</Link></section></main>;
}
