import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const read = (path) => readFileSync(resolve(root, path), "utf8");

const entry = read("App.tsx");
const shell = read("src/NativeApp.tsx");
const secureStorage = read("src/lib/secureStorage.ts");
const cache = read("src/lib/cache.ts");
const api = read("src/lib/api.ts");
const session = read("src/hooks/useBridgeXSession.ts");
const profile = read("src/screens/ProfileScreen.tsx");
const payments = read("src/screens/PaymentsScreen.tsx");
const compose = read("src/screens/ComposeScreen.tsx");
const response = read("src/screens/ResponseScreen.tsx");
const memberProfile = read("src/screens/MemberProfileScreen.tsx");
const more = read("src/screens/MoreScreen.tsx");
const info = read("src/screens/InfoScreen.tsx");
const notifications = read("src/screens/NotificationsScreen.tsx");
const notificationHook = read("src/hooks/useBridgeXNotifications.ts");
const workspaceRecords = read("src/screens/WorkspaceRecordsScreen.tsx");
const marketplace = read("src/screens/MarketplaceScreen.tsx");
const messages = read("src/screens/MessagesScreen.tsx");
const postDetail = read("src/screens/PostDetailScreen.tsx");
const packageJson = read("package.json");
const auth = read("src/components/AuthScreen.tsx");
const managePosts = read("src/screens/ManagePostsScreen.tsx");
const workspaceResponses = read("src/screens/WorkspaceResponsesScreen.tsx");
const paymentGuardMigration = read("../../supabase/migrations/202608221000_native_unread_counts_and_payment_stale_guard.sql");

assert.match(entry, /NativeApp/);
assert.doesNotMatch(entry, /WebView|react-native-webview/);
assert.doesNotMatch(shell, /WebView|https:\/\/bridgex\.abdullahbinfahad\.info/);
assert.match(secureStorage, /SecureStore/);
assert.match(entry, /maybeCompleteAuthSession/);
assert.match(auth, /exchangeCodeForSession/);
assert.match(auth, /passwordVisible/);
assert.match(cache, /AsyncStorage/);
assert.match(session, /flushSafeActions/);
assert.match(api, /createNativeOffer/);
assert.match(api, /upsertNativeListingInterest/);
assert.match(api, /submitNativePaymentProof/);
assert.match(api, /moderateNativeMember/);
assert.match(profile, /uploadNativeVerificationDocument/);
assert.match(payments, /uploadNativePaymentProof/);
assert.match(compose, /acceptedItemBudgets/);
assert.match(compose, /QUANTITY_AWARE_ITEMS/);
assert.match(response, /itemQuantities/);
assert.match(memberProfile, /Public BridgeX posts/);
assert.match(more, /How it works/);
assert.match(info, /Open current website page/);
assert.match(api, /resolveNativeNotificationDestination/);
assert.match(notifications, /onOpenDestination/);
assert.match(notifications, /onEndReached/);
assert.match(notifications, /PAGE_SIZE = 30/);
assert.match(api, /bridgex_native_unread_counts/);
assert.match(api, /registerNativePushToken/);
assert.match(notificationHook, /getExpoPushTokenAsync/);
assert.match(notificationHook, /addNotificationResponseReceivedListener/);
assert.match(workspaceRecords, /Swipeable/);
assert.match(workspaceRecords, /archiveNativeRequest/);
assert.match(shell, /workspace_records/);
assert.match(marketplace, /PRODUCT_CATEGORIES/);
assert.match(marketplace, /categoryFilters/);
assert.match(marketplace, /nativeSignedPostMediaUrl/);
assert.match(marketplace, /VideoView/);
assert.match(messages, /keyboardShouldPersistTaps/);
assert.match(messages, /Platform\.OS === "ios" \? "padding" : "height"/);
assert.match(messages, /native-live-messages/);
assert.match(messages, /mergeMessages/);
assert.match(postDetail, /nativeSignedPostMediaUrl/);
assert.match(postDetail, /DetailVideo/);
assert.match(api, /loadNativeManagedPosts/);
assert.match(api, /updateNativeManagedPost/);
assert.match(api, /loadNativeOwnerResponses/);
assert.match(api, /startNativeOwnerPayment/);
assert.match(api, /p_terms_version: TERMS_VERSION/);
assert.match(managePosts, /Save open post/);
assert.match(workspaceResponses, /Accept & pay/);
assert.match(shell, /workspace_responses/);
assert.match(shell, /initialPaymentId/);
assert.match(shell, /Sign in to manage your profile/);
assert.match(shell, /Sign in to view your updates/);
assert.doesNotMatch(shell, /is ready next\./);
assert.match(paymentGuardMigration, /Another traveler is already the active protected selection/);
assert.match(paymentGuardMigration, /v_offer\.status <> 'pending_payment'/);
assert.doesNotMatch(packageJson, /react-native-webview/);

console.log("BridgeX independent native architecture checks passed.");
